---
sidebar: sidebar 
permalink: trident-docker/deploy-docker.html 
keywords: deploy, astra trident, trident for docker, docker 
summary: Astra Trident for Docker 可直接整合 NetApp 儲存平台的 Docker 生態系統。它支援從儲存平台到Docker主機的儲存資源資源配置與管理、並提供架構、可在未來新增更多平台。 
---
= 部署Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident for Docker 可直接整合 NetApp 儲存平台的 Docker 生態系統。它支援從儲存平台到Docker主機的儲存資源資源配置與管理、並提供架構、可在未來新增更多平台。

多個Astra Trident執行個體可同時在同一個主機上執行。這可同時連線至多個儲存系統和儲存類型、並可自訂Docker磁碟區所使用的儲存設備。

.您需要的產品
請參閱 link:prereqs-docker.html["部署的先決條件"]。在您確定已符合先決條件之後、就可以開始部署Astra Trident。



== Docker託管外掛程式方法（1.1/17.03版及更新版本）

.開始之前

NOTE: 如果您在傳統精靈方法中使用Astra Trident preer Docker 1.3/17.03、請務必先停止Astra Trident程序、然後重新啟動Docker精靈、再使用託管外掛方法。

. 停止所有執行中的執行個體：
+
[listing]
----
pkill /usr/local/bin/netappdvp
pkill /usr/local/bin/trident
----
. 重新啟動Docker。
+
[listing]
----
systemctl restart docker
----
. 請確定您已安裝Docker Engine 17.03（全新1.13）或更新版本。
+
[listing]
----
docker --version
----
+
如果您的版本過時、 https://docs.docker.com/engine/install/["安裝或更新安裝"^]。



.步驟
. 建立組態檔並指定下列選項：
+
** 「config」：預設檔案名稱為「config.json」、但您可以使用任何名稱、只要在檔案名稱中指定「config」選項即可。組態檔必須位於主機系統的「/etc/netappdvp」目錄中。
** 記錄層級：指定記錄層級（「debug」、「info」、「warn」、「f誤差」、「fatal」）。預設值為「資訊」。
** 「Debug」：指定是否啟用偵錯記錄。預設值為假。如果為true、則會置換記錄層級。
+
... 建立組態檔的位置：
+
[listing]
----
sudo mkdir -p /etc/netappdvp
----
... 建立組態檔：
+
[listing]
----
cat << EOF > /etc/netappdvp/config.json
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
EOF
----




. 使用託管外掛系統啟動Astra Trident。更換 `<version>` 使用您所使用的外掛程式版本（xxx.xxx.xx）。
+
[listing]
----
docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:<version> config=myConfigFile.json
----
. 開始使用Astra Trident來消耗已設定系統的儲存空間。
+
.. 建立名為「firstVolume」的Volume：
+
[listing]
----
docker volume create -d netapp --name firstVolume
----
.. 在容器啟動時建立預設Volume：
+
[listing]
----
docker run --rm -it --volume-driver netapp --volume secondVolume:/my_vol alpine ash
----
.. 移除Volume「firstVolume」：
+
[listing]
----
docker volume rm firstVolume
----






== 傳統方法（1.12版或更早版本）

.開始之前
. 請確定您擁有Docker 1.10版或更新版本。
+
[listing]
----
docker --version
----
+
如果您的版本已過時、請更新安裝。

+
[listing]
----
curl -fsSL https://get.docker.com/ | sh
----
+
或者、 https://docs.docker.com/engine/install/["請依照您的經銷指示進行"^]。

. 確保已為您的系統設定NFS和/或iSCSI。


.步驟
. 安裝及設定NetApp Docker Volume外掛程式：
+
.. 下載並解壓縮應用程式：
+
[listing]
----
wget https://github.com/NetApp/trident/releases/download/v23.07.0/trident-installer-23.07.0.tar.gz
tar zxf trident-installer-23.07.0.tar.gz
----
.. 移至Bin路徑中的位置：
+
[listing]
----
sudo mv trident-installer/extras/bin/trident /usr/local/bin/
sudo chown root:root /usr/local/bin/trident
sudo chmod 755 /usr/local/bin/trident
----
.. 建立組態檔的位置：
+
[listing]
----
sudo mkdir -p /etc/netappdvp
----
.. 建立組態檔：
+
[listing]
----
cat << EOF > /etc/netappdvp/ontap-nas.json
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
EOF
----


. 放置二進位檔案並建立組態檔案之後、請使用所需的組態檔案啟動 Trident 精靈。
+
[listing]
----
sudo trident --config=/etc/netappdvp/ontap-nas.json
----
+

NOTE: 除非指定、否則 Volume 驅動程式的預設名稱為「 NetApp 」。

+
精靈啟動後、您可以使用Docker CLI介面來建立及管理磁碟區

. 建立Volume：
+
[listing]
----
docker volume create -d netapp --name trident_1
----
. 在啟動容器時配置Docker Volume：
+
[listing]
----
docker run --rm -it --volume-driver netapp --volume trident_2:/my_vol alpine ash
----
. 移除Docker Volume：
+
[listing]
----
docker volume rm trident_1
docker volume rm trident_2
----




== 在系統啟動時啟動Astra Trident

如需系統型系統的單元檔案範例、請參閱 `contrib/trident.service.example` 在Git repo中。若要搭配RHEL使用檔案、請執行下列步驟：

. 將檔案複製到正確的位置。
+
如果執行多個執行個體、則應使用單元檔案的唯一名稱。

+
[listing]
----
cp contrib/trident.service.example /usr/lib/systemd/system/trident.service
----
. 編輯檔案、變更說明（第2行）以符合驅動程式名稱和組態檔案路徑（第9行）、以反映您的環境。
. 重新載入系統d以擷取變更：
+
[listing]
----
systemctl daemon-reload
----
. 啟用服務。
+
此名稱會根據您在「/r/lib/systemd/system]目錄中命名的檔案而有所不同。

+
[listing]
----
systemctl enable trident
----
. 啟動服務。
+
[listing]
----
systemctl start trident
----
. 檢視狀態。
+
[listing]
----
systemctl status trident
----



NOTE: 每當您修改單元檔案時、請執行「stystemctl daem-reload」命令、以瞭解變更內容。
