---
sidebar: sidebar 
permalink: trident-docker/known-issues-docker.html 
keywords: known issues, trident, trident for docker, docker 
summary: 在搭配 Docker 使用 Trident 時、尋找已知問題的相關資訊。 
---
= 已知問題與限制
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在搭配 Docker 使用 Trident 時、尋找已知問題和限制的相關資訊。



== 從舊版升級Trident Docker Volume外掛程式至20.10及更新版本、會導致升級失敗、且不會發生此類檔案或目錄錯誤。

.因應措施
. 停用外掛程式。
+
[source, console]
----
docker plugin disable -f netapp:latest
----
. 移除外掛程式。
+
[source, console]
----
docker plugin rm -f netapp:latest
----
. 提供額外的「config」參數、重新安裝外掛程式。
+
[source, console]
----
docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json
----




== Volume名稱長度必須至少2個字元。


NOTE: 這是Docker用戶端的限制。用戶端會將單一字元名稱解譯為Windows路徑。 https://github.com/moby/moby/issues/25773["請參閱錯誤25773"^]。



== Docker swarm 具有某些行為、可防止 Trident 在每個儲存設備和驅動程式組合中支援它。

* Docker swarm目前使用Volume名稱、而非Volume ID做為其唯一的Volume識別碼。
* Volume要求會同時傳送至swarm叢集中的每個節點。
* Volume 外掛程式（包括 Trident ）必須在 swarm 叢集中的每個節點上分別執行。由於 ONTAP 的運作方式、以及和 `ontap-san`驅動程式的運作方式 `ontap-nas`、這些都是唯一能夠在這些限制範圍內運作的方法。


其餘的驅動程式可能會遇到競爭條件等問題，導致在沒有明確「贏家」的情況下，為單一要求建立大量磁碟區；例如， Element 具有允許磁碟區擁有相同名稱但不同 ID 的功能。

NetApp已向Docker團隊提供意見回饋、但沒有任何未來追索的跡象。



== 如果配置的是某個功能區、則如果第二個功能區的一個或多個集合體與要配置的功能區相同、則不提供第二個功能區。FlexGroup ONTAP FlexGroup FlexGroup FlexGroup
