---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, astra trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config 
summary: 您必須先在主機上安裝並設定必要的傳輸協定先決條件、才能部署Astra Trident。 
---
= 部署的先決條件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須先在主機上安裝並設定必要的傳輸協定先決條件、才能部署Astra Trident。



== 驗證需求

* 確認您的部署符合所有的 link:../trident-get-started/requirements.html["需求"]。
* 確認您安裝的Docker版本受支援。如果您的Docker版本過時、 https://["安裝或更新"^]。
+
[listing]
----
docker --version
----
* 確認已在您的主機上安裝及設定通訊協定先決條件：


[cols="3*"]
|===
| 傳輸協定 | 作業系統 | 命令 


| NFS  a| 
RHEL 8以上
 a| 
「Udo yum install -y ns-utils」



| NFS  a| 
Ubuntu
 a| 
「Udo apt-Get install -y nfs通用」



| iSCSI  a| 
RHEL 8以上
 a| 
. 安裝下列系統套件：
+
「Udo yum install -y lsscsi iscsi-initiator－utils sg3_utils device-mapper-multipath'

. 檢查iscsite-initier-utils版本是否為6.6.0.874-2.el7或更新版本：
+
「rpm -q iscsiscsiscs-initier-utils」

. 將掃描設為手動：
+
「Udo sed -I 's/^\（node.session.scan\).*/\1 = manual /」/etc/iscsi/iscsid.conf）

. 啟用多重路徑：
+
「Udo mpathconf --enable --with _docathd y --fisco_multipaths n」

+

NOTE: 確保在"default"（錯誤）下"etc/multipath.conf"包含"fappe_multipaths no"。

. 確保運行的是"iscsid"和"multipathd"：
+
「啟用Udo systemctl -現在是iscsid多路徑」

. 啟用並啟動「iSCSI」：
+
「Udo systemctl enable - NOW iSCSI」





| iSCSI  a| 
Ubuntu
 a| 
. 安裝下列系統套件：
+
「Udo apt-Get install -y open-iscsi sg3-utils multipath-tools scsitols」

. 檢查開放式iSCSI版本是否為2.0.874-5ubuntu2．10或更新版本（適用於雙聲網路）或2.0.874-7.1ubuntu6.1或更新版本（適用於焦點）：
+
「Dpkg -l open-iscsi」

. 將掃描設為手動：
+
「Udo sed -I 's/^\（node.session.scan\).*/\1 = manual /」/etc/iscsi/iscsid.conf）

. 啟用多重路徑：
+
「Udo tee /etc/multipath.conf」<<-'EOF'預設值｛user_易 記名稱yes focs_multipaths no｝EOF Sudo systemctl enable --NOW multipath-tools.service Sudo服務multipath-ttools restart」

+

NOTE: 確保在"default"（錯誤）下"etc/multipath.conf"包含"fappe_multipaths no"。

. 確保已啟用並執行「open-iscsi」和「多路徑工具」：
+
「Udo systemctl狀態multipath-ttools/」「show systemcl enable -現在open-iscsi.service`「show systemctl狀態open-iscsi」



|===