---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: 請參閱 Trident 組態可用的組態選項。 
---
= 儲存組態選項
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請參閱 Trident 組態可用的組態選項。



== 全域組態選項

無論使用的儲存平台為何、這些組態選項都適用於所有 Trident 組態。

[cols="3*"]
|===
| 選項 | 說明 | 範例 


| 「分度」  a| 
組態檔版本編號
 a| 
`1`



| 「torageDriverName」  a| 
儲存驅動程式名稱
 a| 
`ontap-nas`、 `ontap-san`、 `ontap-nas-economy`、
`ontap-nas-flexgroup`、 `solidfire-san`



| 「toragePrefix」  a| 
Volume名稱的選用首碼。預設： `netappdvp_`。
 a| 
`staging_`



| 《限制Volume大小》  a| 
Volume大小的選擇性限制。預設： "" （未強制執行）
 a| 
`10g`

|===

TIP: 請勿將（包括預設值）用於 `storagePrefix`元素後端。根據預設、 `solidfire-san`驅動程式會忽略此設定、而不使用前置碼。NetApp 建議您使用特定的 TenantId 來進行 Docker Volume 對應，或是使用包含 Docker 版本，驅動程式資訊和 Docker 原始名稱的屬性資料，以供任何名稱佔用。

您可以使用預設選項、避免在每個建立的Volume上指定這些選項。「最小化」選項適用於所有控制器類型。如ONTAP 需如何設定預設Volume大小的範例、請參閱「功能區組態」一節。

[cols="3*"]
|===
| 選項 | 說明 | 範例 


| 《大小》  a| 
新磁碟區的選用預設大小。預設： `1G`
 a| 
`10G`

|===


== 組態ONTAP

除了上述全域組態值之外、使用ONTAP 時還提供下列頂層選項。

[cols="3*"]
|===
| 選項 | 說明 | 範例 


| 《馬納格門達利》  a| 
IP位址ONTAP ：您可以指定完整網域名稱（FQDN）。
 a| 
`10.0.0.1`



| 「DataLIF」  a| 
傳輸協定LIF的IP位址。

* ONTAP NAS 驅動程序 * ： NetApp 建議指定 `dataLIF`。如果未提供， Trident 會從 SVM 擷取 dataLIFs 。您可以指定完整網域名稱（ FQDN ），以用於 NFS 裝載作業，讓您建立循環 DNS ，以便在多個 dataLIFs 之間進行負載平衡。

* ONTAP SAN 驅動程式 * ：請勿指定 iSCSI 或 FC 。Trident 使用link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["可選擇的LUN對應ONTAP"^]來探索建立多重路徑工作階段所需的 iSCSI 或 FC 生命負載。如果明確定義、就會產生警告 `dataLIF`。
 a| 
`10.0.0.2`



| 《虛擬機器》  a| 
要使用的儲存虛擬機器（如果管理LIF是叢集LIF、則為必要）
 a| 
`svm_nfs`



| 《使用者名稱》  a| 
連線至儲存設備的使用者名稱
 a| 
`vsadmin`



| 密碼  a| 
連線至儲存設備的密碼
 a| 
`secret`



| 《Aggregate》  a| 
用於資源配置的Aggregate（選用；如果已設定、則必須指派給SVM）。對於 `ontap-nas-flexgroup`驅動程式、此選項會被忽略。指派給 SVM 的所有集合體都會用於佈建 FlexGroup Volume 。
 a| 
`aggr1`



| 「限制Aggregateusage」  a| 
如果使用率高於此百分比、則可選用、失敗的資源配置
 a| 
`75%`



| 「nfsMountOptions」  a| 
精細控制 NFS 裝載選項；預設為「 -o nfsver=3 」。* 僅適用於 `ontap-nas`和 `ontap-nas-economy`驅動程式 * 。 https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["請參閱此處的NFS主機組態資訊"^]。
 a| 
`-o nfsvers=4`



| 「igroupName」  a| 
Trident 會以 `netappdvp`建立及管理每個節點 `igroups`。

此值不可變更或省略。

*僅適用於 `ontap-san` 驅動程式 * 。
 a| 
`netappdvp`



| 《限制Volume大小》  a| 
可要求的最大磁碟區大小。
 a| 
`300g`



| "qtreesPerFlexvol"  a| 
每FlexVol 個邊區最多qtree數、範圍必須為[50、300]、預設值為200。

*適用於 `ontap-nas-economy` 驅動程式、此選項可自訂每FlexVol 個版本的qtree數量上限*。
 a| 
`300`



 a| 
`sanType`
| * 僅支援 `ontap-san`驅動程式。 *用於選擇 `iscsi` iSCSI 、 `nvme` NVMe / TCP 或 `fcp` SCSI over Fibre Channel （ FC ）。 | `iscsi` 如果空白 


| `limitVolumePoolSize` | * `ontap-san-economy` `ontap-san-economy` 僅支援和驅動程式。 *在 ONTAP ONTAP NAS 經濟型和 ONTAP SAN 經濟型驅動程式中限制 FlexVol 大小。  a| 
`300g`

|===
您可以使用預設選項、避免在您建立的每個Volume上指定這些選項：

[cols="1,3,2"]
|===
| 選項 | 說明 | 範例 


| 《保護區》  a| 
空間保留模式； `none` （精簡配置）或 `volume` （粗）
 a| 
無



| 「快照原則」  a| 
要使用的 Snapshot 原則、預設為 `none`
 a| 
無



| 「快照保留區」  a| 
Snapshot 保留百分比，預設為「」接受 ONTAP 預設值
 a| 
`10`



| 「PlitOnClone」  a| 
建立複本時、將其父複本分割成預設值 `false`
 a| 
「假」



| 加密  a| 
在新磁碟區上啟用NetApp Volume Encryption（NVE）；預設為「假」。必須在叢集上授權並啟用NVE、才能使用此選項。

如果在後端啟用 NAE 、則 Trident 中配置的任何 Volume 都將啟用 NAE 。

如需更多資訊、請參閱link:../trident-reco/security-reco.html["Trident 如何與 NVE 和 NAE 搭配運作"]：。
 a| 
是的



| 「unixPermissions」  a| 
NAS 選項適用於已佈建的 NFS 磁碟區、預設為 `777`
 a| 
`777`



| 「napshotDir  a| 
用於存取目錄的 NAS 選項 `.snapshot`。
 a| 
針對 NFSv3 的 NFSv4 "false" 為 "true"



| 「匯出政策」  a| 
NFS 匯出原則使用的 NAS 選項、預設為 `default`
 a| 
`default`



| 《生態樣式》  a| 
NAS選項、可存取已配置的NFS Volume。

NFS支援 `mixed` 和 `unix` 安全樣式：預設值為 `unix`。
 a| 
`unix`



| 「fileSystemType」  a| 
SAN 選項可選擇檔案系統類型、預設為 `ext4`
 a| 
`xfs`



| 「分層政策」  a| 
要使用的分層原則，預設為 `none`。
 a| 
無

|===


=== 擴充選項

 `ontap-nas`和 `ontap-san`驅動程式會為每個 Docker Volume 建立 ONTAP FlexVol 。ONTAP 每個叢集節點最多可支援 1000 個 FlexVols ，叢集最多 12 ， 000 個 FlexVol Volume 。如果您的 Docker Volume 需求符合這項限制，則 `ontap-nas`由於 FlexVols 提供的額外功能（例如 Docker Volume 精細快照和複製），因此驅動程式是首選的 NAS 解決方案。

如果您需要的Docker磁碟區數量超過FlexVol 了《支援》的範圍、請選擇「ONTAP - NAS經濟」或「ONTAP - SAN經濟」驅動程式。

此 `ontap-nas-economy`驅動程式會在自動管理的 FlexVol Volume 集區內，以 ONTAP qtree 的形式建立 Docker Volume 。qtree的擴充能力大幅提升、每個叢集節點最多可達100、000個、每個叢集最多可達2、400、000個、而犧牲了部分功能。此 `ontap-nas-economy`驅動程式不支援 Docker Volume 精細快照或複製。


NOTE: Docker swarm 目前不支援此 `ontap-nas-economy`驅動程式，因為 Docker swarm 不會在多個節點之間協調磁碟區建立。

此 `ontap-san-economy`驅動程式會在自動管理的 FlexVol 磁碟區的共用集區中，將 Docker 磁碟區建立為 ONTAP LUN 。如此FlexVol 一來、每個支援不只侷限於一個LUN、而且能為SAN工作負載提供更好的擴充性。根據儲存陣列的不同、ONTAP 每個叢集最多可支援16384個LUN。由於磁碟區是下方的LUN、因此此驅動程式支援Docker磁碟區精細快照和複製。

選擇 `ontap-nas-flexgroup`驅動程式來增加單一磁碟區的平行度、使其可擴充至數十億個檔案的 PB 範圍。FlexGroups的一些理想使用案例包括AI / ML / DL、Big Data和分析、軟體建置、串流、檔案儲存庫等。Trident 會在佈建 FlexGroup Volume 時、使用指派給 SVM 的所有集合體。支援Trident也有下列考量：FlexGroup

* 需要ONTAP 9.2版或更新版本。
* 截至本文撰寫時、FlexGroups僅支援NFS v3。
* 建議啟用SVM的64位元NFSv3識別碼。
* 建議的 FlexGroup 成員 / 磁碟區大小下限為 100GiB 。
* FlexGroup 磁碟區不支援複製。


有關適用於 FlexGroups 的 FlexGroups 和工作負載的資訊，請參閱 https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetApp FlexGroup Volume 最佳實務做法與實作指南"^]。

若要在同一個環境中取得進階功能和大規模功能，您可以使用執行多個 Docker Volume 外掛程式執行個體，其中一個使用，另 `ontap-nas-economy`一個使用 `ontap-nas`。



=== Trident 的自訂 ONTAP 角色

您可以使用最低 Privileges 來建立 ONTAP 叢集角色、這樣就不需要使用 ONTAP 管理員角色來執行 Trident 中的作業。當您在 Trident 後端組態中包含使用者名稱時、 Trident 會使用您建立的 ONTAP 叢集角色來執行作業。

如需建立 Trident 自訂角色的詳細資訊、請參閱link:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Trident 自訂角色產生器"]。

[role="tabbed-block"]
====
.使用 ONTAP CLI
--
. 使用下列命令建立新角色：
+
`security login role create <role_name\> -cmddirname "command" -access all -vserver <svm_name\>`

. 為 Trident 使用者建立使用者名稱：
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`

. 將角色對應至使用者：
+
`security login modify username <user_name\> -vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.使用System Manager
--
在 ONTAP 系統管理員中執行下列步驟：

. * 建立自訂角色 * ：
+
.. 若要在叢集層級建立自訂角色、請選取 * 叢集 > 設定 * 。
+
（或）若要在 SVM 層級建立自訂角色、請選取 * 儲存設備 > 儲存 VM > > `required SVM` 設定 > 使用者與角色 * 。

.. 選取 * 使用者和角色 * 旁的箭頭圖示（ * -> * ）。
.. 在 * 角色 * 下選擇 *+Add* 。
.. 定義角色的規則、然後按一下 * 儲存 * 。


. * 將角色對應至 Trident 使用者 * ： + 在「 * 使用者與角色 * 」頁面上執行下列步驟：
+
.. 在 * 使用者 * 下選取新增圖示 *+* 。
.. 選取所需的使用者名稱、然後在 * 角色 * 的下拉式功能表中選取角色。
.. 按一下「 * 儲存 * 」。




--
====
如需詳細資訊、請參閱下列頁面：

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["用於管理 ONTAP 的自訂角色"^]或link:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["定義自訂角色"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["與角色和使用者合作"^]




=== 範例ONTAP ：功能組態檔

.<code>ontap-nas</code> 驅動程式的 NFS 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "defaults": {
    "size": "10G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.<code>ontap-nas-flexgroup</code> 驅動程式的 NFS 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-flexgroup",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "defaults": {
    "size": "100G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.<code>ontap-nas-economy</code> 驅動程式的 NFS 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
----
====
.<code>ontap-san</code> 驅動程式的 iSCSI 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.<code>ontap-san-economy</code> 驅動程式的 NFS 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi_eco",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.<code>ontap-san</code> 驅動程式的 NVMe / TCP 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username": "vsadmin",
  "password": "password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.SCSI over FC 範例，適用於 <code> ONTAP － </code> 驅動程式
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username": "vsadmin",
  "password": "password",
  "useREST": true
}
----
====


== 元件軟體組態

除了全域組態值之外、使用Element軟體（NetApp HCI / SolidFire）時、也可使用這些選項。

[cols="3*"]
|===
| 選項 | 說明 | 範例 


| 端點  a| 
\https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| 《VIP》  a| 
iSCSI IP位址和連接埠
 a| 
10.0.0.7：3260



| 《天王名稱》  a| 
要使用的SolidFireF租戶（如果找不到、請建立）
 a| 
`docker`



| 《初始器IFACE》  a| 
將iSCSI流量限制為非預設介面時、請指定介面
 a| 
`default`



| 《類型》  a| 
QoS規格
 a| 
請參閱以下範例



| "LegacyNamePrefix（名前置詞）"  a| 
升級版Trident安裝的首碼。如果您使用 1.3.2 之前的 Trident 版本、並使用現有的 Volume 執行升級、則必須設定此值、才能存取透過 Volume 名稱方法對應的舊 Volume 。
 a| 
`netappdvp-`

|===
「Poolidfire - san」驅動程式不支援Docker swarm。



=== 元素軟體組態檔範例

[source, json]
----
{
  "version": 1,
  "storageDriverName": "solidfire-san",
  "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
  "SVIP": "10.0.0.7:3260",
  "TenantName": "docker",
  "InitiatorIFace": "default",
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----