---
sidebar: sidebar 
permalink: trident-docker/volume-driver-options.html 
keywords: create volumes, astra trident, trident for docker, docker, docker volume, driver options, ontap, element volumes, cvs, cloud volumes service on gcp, azure netapp files 
summary: 每個儲存驅動程式都有一組不同的選項、您可以在建立磁碟區時指定、以自訂結果。請參閱下方、以瞭解適用於您所設定儲存系統的選項。 
---
= 驅動程式專屬的Volume選項
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個儲存驅動程式都有一組不同的選項、您可以在建立磁碟區時指定、以自訂結果。請參閱下方、以瞭解適用於您所設定儲存系統的選項。

在磁碟區建立作業期間使用這些選項非常簡單。在CLI操作期間、使用「-o」運算子來提供選項和值。這會覆寫Json組態檔中的任何等效值。



== 選購的選購配備ONTAP

NFS和iSCSI的Volume建立選項包括：

[cols="2*"]
|===
| 選項 | 說明 


| 《大小》  a| 
Volume的大小、預設為1 GiB。



| 《保護區》  a| 
精簡或完整配置磁碟區、預設為精簡。有效值為「NONE」（精簡配置）和「Volume」（完整配置）。



| 「快照原則」  a| 
這會將快照原則設定為所需的值。預設值為「無」、表示不會自動建立磁碟區的快照。除非您的儲存管理員加以修改、否則ONTAP 所有的各種系統都會有一個名為「預設」的原則、用來建立並保留六個每小時、每天兩個和每週兩個快照。快照中保留的資料可透過瀏覽至磁碟區任何目錄中的「.snapshot」目錄來還原。



| 「快照保留區」  a| 
這會將快照保留設定為所需的百分比。預設值為無值、表示ONTAP 如果您已選取snapshotPolicy、將選取snapshotReserve（通常為5%）、如果snapshotPolicy為無、則選取0%。您可以在組態檔中為所有ONTAP 的支援項目設定預設的snapshotReserve值、也可以將其用作所有ONTAP 不支援ONTAP-NAS-經濟功能的支援項目、作為所有支援項目的磁碟區建立選項。



| 「PlitOnClone」  a| 
當複製Volume時、ONTAP 這會導致停止實體複本、立即將其從父複本分割開來。預設值為「假」。部分複製磁碟區的使用案例、最好是在建立時立即將複本從父複本分割出來、因為不太可能有提高儲存效率的機會。例如，複製空白資料庫可節省大量時間，但儲存空間卻很少，因此最好立即分割實體複本。



| 加密  a| 
在新磁碟區上啟用NetApp Volume Encryption（NVE）；預設為「假」。必須在叢集上授權並啟用NVE、才能使用此選項。

如果在後端啟用NAE、則Astra Trident中配置的任何磁碟區都會啟用NAE。

如需詳細資訊、請參閱： link:../trident-reco/security-reco.html["Astra Trident如何與NVE和NAE搭配運作"]。



| 「分層政策」  a| 
設定要用於磁碟區的分層原則。這會決定資料在非作用中（冷）時是否移至雲端層。

|===
下列其他選項適用於NFS * Only *：

[cols="2*"]
|===
| 選項 | 說明 


| 「unixPermissions」  a| 
這會控制Volume本身的權限設定。依預設、權限會設為「-rwxr-x-x'」、或是以數字表示法0755、而「root」則是擁有者。文字或數字格式皆可運作。



| 「napshotDir  a| 
如果將此目錄設為「true」、則會讓存取磁碟區的用戶端看到「.snapshot」目錄。預設值為「假」、表示預設會停用「.snapshot」目錄的可見度。某些影像（例如官方MySQL映像）在出現「.snapshot」目錄時無法如預期般運作。



| 「匯出政策」  a| 
設定要用於磁碟區的匯出原則。預設值為「預設」。



| 《生態樣式》  a| 
設定用於存取磁碟區的安全樣式。預設值為「UNIX」。有效值為「UNIX」和「mixed」。

|===
下列其他選項僅適用於iSCSI *：

[cols="2*"]
|===
| 選項 | 說明 


| 「fileSystemType」 | 設定用於設定iSCSI磁碟區格式的檔案系統。預設值為「ext4」。有效值包括「ext3」、「ext4」和「xfs」。 


| "paceAllocate（配置）" | 如果將此值設為「假」、將會關閉LUN的空間分配功能。預設值為「true」、表示ONTAP 當磁碟區空間不足、且磁碟區中的LUN無法接受寫入時、功能區會通知主機。此選項也可讓ONTAP 支援功能在主機刪除資料時自動回收空間。 
|===


=== 範例

請參閱下列範例：

* 建立10GiB Volume：
+
[listing]
----
docker volume create -d netapp --name demo -o size=10G -o encryption=true
----
* 使用快照建立100GiB磁碟區：
+
[listing]
----
docker volume create -d netapp --name demo -o size=100G -o snapshotPolicy=default -o snapshotReserve=10
----
* 建立已啟用setuid位元的磁碟區：
+
[listing]
----
docker volume create -d netapp --name demo -o unixPermissions=4755
----


最小Volume大小為20MiB。

如果未指定快照保留、且快照原則為「無」、Trident將使用快照保留0%。

* 建立沒有快照原則且無快照保留的磁碟區：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none
----
* 建立不含快照原則的磁碟區、以及自訂快照保留10%的磁碟區：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none --opt snapshotReserve=10
----
* 建立具有快照原則和10%自訂快照保留的磁碟區：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy --opt snapshotReserve=10
----
* 使用快照原則建立磁碟區、並接受ONTAP的預設快照保留（通常為5%）：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy
----




== Element軟體Volume選項

元素軟體選項會顯示與磁碟區相關的服務品質（QoS）原則大小和品質。建立磁碟區時、會使用「-o type =service_level」命名法來指定與其相關的QoS原則。

使用元素驅動程式定義QoS服務層級的第一步、是建立至少一種類型、並在組態檔中指定與名稱相關的最小、最大和尖峰IOPS。

其他元素軟體磁碟區建立選項包括：

[cols="2*"]
|===
| 選項 | 說明 


| 《大小》  a| 
磁碟區大小、預設為1GiB或組態項目... 「預設值」：｛"Size"："5G"｝。



| 「區塊大小」  a| 
使用512或4096、預設為512或組態項目預設BlockSizes。

|===


=== 範例

請參閱下列QoS定義範例組態檔：

[listing]
----
{
    "...": "..."
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----
在上述組態中、我們有三種原則定義：銅級、銀級和金級。這些名稱為任意名稱。

* 建立10GiB Gold Volume：
+
[listing]
----
docker volume create -d solidfire --name sfGold -o type=Gold -o size=10G
----
* 建立100GiB銅級磁碟區：
+
[listing]
----
docker volume create -d solidfire --name sfBronze -o type=Bronze -o size=100G
----

