---
settings:
  name: Astra Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: trident-rn.html
  versions:
  - name: Astra Trident
    url: "/trident"
    version-number: '23.04'
  - name: Astra Trident
    url: "/trident-2301"
    version-number: '23.01'
  - name: Astra Trident
    url: "/trident-2210"
    version-number: '22.10'
  - name: Astra Trident
    url: "/trident-2207"
    version-number: '22.07'
  - name: Astra Trident
    url: "/trident-2204"
    version-number: '22.04'
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Astra Trident文件
    url: "/index.html"
  - title: 版本資訊
    entries:
    - title: 新增功能
      url: "/trident-rn.html"
    - title: 舊版
      url: "/earlier-versions.html"
  - section: trident-concepts
  - section: trident-get-started
  - section: trident-managing-k8s
  - section: trident-use
  - section: trident-docker
  - title: 常見問題集
    url: "/faq.html"
  - title: 支援
    url: "/get-help.html"
  - title: 疑難排解
    url: "/troubleshooting.html"
  - section: trident-reco
  - section: trident-reference
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: 所有Astra文件
