---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, Trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: 您應該使用與安裝 Trident 相同的方法來解除安裝 Trident 。如果您需要修正在升級、相依性問題或升級失敗或不完整之後所觀察到的錯誤、您應該解除安裝 Trident 、並使用該版本的特定指示重新安裝舊版。 
---
= 解除安裝Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該使用與安裝 Trident 相同的方法來解除安裝 Trident 。

.關於這項工作
* 如果您需要修正在升級、相依性問題或升級失敗或不完整之後所觀察到的錯誤，您應該解除安裝 Trident ，並使用該的特定指示重新安裝舊版link:../earlier-versions.html["版本"]。這是將 _ 降級 _ 降級至較早版本的唯一建議方法。
* 為了方便升級和重新安裝、解除安裝 Trident 並不會移除 Trident 所建立的 CRD 或相關物件。如果您需要完全移除 Trident 及其所有資料、請參閱link:../troubleshooting.html#completely-remove-trident-and-crds["完全移除 Trident 和客戶需求日"]。


.開始之前
如果您要停用 Kubernetes 叢集、則必須先刪除所有使用 Trident 建立之 Volume 的應用程式、然後再解除安裝。如此可確保在刪除之前、不會在 Kubernetes 節點上發佈 PVC 。



== 確定原始安裝方法

您應該使用與安裝相同的方法來解除安裝 Trident 。在解除安裝之前、請先確認您原本安裝 Trident 的版本。

. 使用 `kubectl get pods -n trident` 檢查 Pod 。
+
** 如果沒有運算子 Pod 、則使用安裝 Trident `tridentctl` 。
** 如果有操作員 Pod 、則 Trident 是使用 Trident 操作員手動或使用 Helm 來安裝。


. 如果有操作員 Pod 、請使用 `kubectl describe tproc trident`判斷是否使用 Helm 安裝 Trident 。
+
** 如果有 Helm 標籤、則使用 Helm 安裝 Trident 。
** 如果沒有 Helm 標籤、則會使用 Trident 操作員手動安裝 Trident 。






== 解除安裝 Trident 運算子安裝

您可以手動或使用 Helm 解除安裝 Trident 運算子安裝。



=== 解除安裝手動安裝

如果您使用運算子安裝 Trident 、則可以執行下列其中一項動作來解除安裝：

. 編輯 `TridentOrchestrator` CR 並設定解除安裝旗標 ** ：
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
當 `uninstall` 旗標設定為 `true`、Trident運算子會卸載Trident、但不會移除TridentOrchestrator本身。如果您想要再次安裝Trident、請清理TridentOrchestrator並建立新的Trident。

. ** 刪除 `TridentOrchestrator`** ：移除用於部署 Trident 的 CR 後 `TridentOrchestrator`、您會指示操作員解除安裝 Trident 。操作員會處理移除並繼續移除 Trident 部署和取消程式集、刪除其在安裝過程 `TridentOrchestrator`中所建立的 Trident Pod 。
+
[listing]
----
kubectl delete -f deploy/<bundle.yaml> -n <namespace>
----




=== 解除安裝 Helm 安裝

如果您使用 Helm 安裝 Trident 、可以使用解除安裝 `helm uninstall`。

[listing]
----
#List the Helm release corresponding to the Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== 解除安裝 `tridentctl` 安裝

使用 `uninstall`中的命令 `tridentctl`移除與 Trident 相關的所有資源、但 CRD 和相關物件除外：

[listing]
----
./tridentctl uninstall -n <namespace>
----