---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, astra trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: 您應該使用與安裝 Astra Trident 相同的方法來解除安裝 Astra Trident 。如果您需要修正在升級、相依性問題或升級失敗或不完整之後所觀察到的錯誤、您應該解除安裝 Astra Trident 、並使用該版本的特定指示重新安裝舊版。 
---
= 解除安裝Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該使用與安裝 Astra Trident 相同的方法來解除安裝 Astra Trident 。

.關於這項工作
* 如果您需要修正升級、相依性問題或升級失敗或不完整之後所觀察到的錯誤、您應該解除安裝 Astra Trident 、並使用相關的特定指示重新安裝舊版 link:../earlier-versions.html["版本"]。這是將 _ 降級 _ 降級至較早版本的唯一建議方法。
* 為了方便升級和重新安裝、解除安裝 Astra Trident 並不會移除 Astra Trident 所建立的 CRD 或相關物件。如果您需要完全移除 Astra Trident 及其所有資料、請參閱 link:../troubleshooting.html#completely-remove-astra-trident-and-crds["完全移除 Astra Trident 和 CRD"]。


.開始之前
如果您要停用 Kubernetes 叢集、則必須先刪除所有使用 Astra Trident 所建立之 Volume 的應用程式、然後再解除安裝。如此可確保在刪除之前、不會在 Kubernetes 節點上發佈 PVC 。



== 確定原始安裝方法

您應該使用與安裝 Astra Trident 相同的方法來解除安裝 Astra Trident 。在解除安裝之前、請先確認您原本用來安裝 Astra Trident 的版本。

. 使用 `kubectl get pods -n trident` 檢查 Pod 。
+
** 如果沒有操作員 Pod 、則使用安裝 Astra Trident `tridentctl`。
** 如果有操作員 Pod 、則使用 Trident 操作員手動或使用 Helm 來安裝 Astra Trident 。


. 如果有操作員 Pod 、請使用 `kubectl describe tproc trident` 判斷 Astra Trident 是否使用 Helm 安裝。
+
** 如果有 Helm 標籤、則使用 Helm 安裝 Astra Trident 。
** 如果沒有 Helm 標籤、則使用 Trident 運算子手動安裝 Astra Trident 。






== 解除安裝 Trident 運算子安裝

您可以手動或使用 Helm 解除安裝 Trident 運算子安裝。



=== 解除安裝手動安裝

如果您使用運算子安裝 Astra Trident 、您可以執行下列其中一項動作來解除安裝：

. 編輯 `TridentOrchestrator` CR 並設定解除安裝旗標 ** ：
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
當 `uninstall` 旗標設定為 `true`、Trident運算子會卸載Trident、但不會移除TridentOrchestrator本身。如果您想要再次安裝Trident、請清理TridentOrchestrator並建立新的Trident。

. 刪除 `TridentOrchestrator`** ：移除 `TridentOrchestrator` 用來部署Astra Trident的CR、您可以指示操作員解除安裝Trident。操作員會處理的移除作業 `TridentOrchestrator` 然後繼續移除Astra Trident部署和取消安裝、刪除它在安裝過程中建立的Trident Pod。




=== 解除安裝 Helm 安裝

如果您使用Helm安裝Astra Trident、您可以使用「helm uninstall」來解除安裝。

[listing]
----
#List the Helm release corresponding to the Astra Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== 解除安裝 `tridentctl` 安裝

使用 `uninstall` 命令輸入 `tridentctl` 若要移除與 Astra Trident 相關的所有資源、但 CRD 和相關物件除外：

[listing]
----
./tridentctl uninstall -n <namespace>
----