---
sidebar: sidebar 
permalink: trident-use/backend_ops_kubectl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, kubectl, create backends, delete backends, update backends, view backends 
summary: 瞭解如何使用「kubecll」來執行後端管理作業。 
---
= 以KECBECVL執行後端管理
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


瞭解如何使用「kubecll」來執行後端管理作業。



== 刪除後端

刪除「TridentBackendConfig」（TridentBackendConfig）之後、即指示Astra Trident刪除/保留後端（根據「刪除原則」）。若要刪除後端、請確定「刪除原則」已設定為刪除。如果只要刪除「TridentBackendConfig」、請確定「刪除原則」已設定為保留。這可確保後端仍存在、並可使用「tridentctl」進行管理。

執行下列命令：

[listing]
----
kubectl delete tbc <tbc-name> -n trident
----
Astra Trident並不會刪除「TridentBackendConfig」所使用的Kubernetes Secrets。Kubernetes使用者負責清除機密。刪除機密時必須小心。只有在後端未使用機密時、才應刪除這些機密。



== 檢視現有的後端

執行下列命令：

[listing]
----
kubectl get tbc -n trident
----
您也可以執行「tridentctl Get backend -n trident」或「tridentctl Get backend -o yaml -n trident」、以取得所有後端的清單。這份清單也會包含以「tridentctl」建立的後端。



== 更新後端

更新後端可能有多種原因：

* 儲存系統的認證資料已變更。若要更新認證資料、必須更新「TridentBackendConfig」物件中使用的Kubernetes Secret。Astra Trident會自動以提供的最新認證資料更新後端。執行下列命令以更新Kubernetes Secret：


[listing]
----
kubectl apply -f <updated-secret-file.yaml> -n trident
----
* 需要ONTAP 更新參數（例如使用的SVM名稱）。在這種情況下、「TridentBackendConfig」物件可直接透過Kubernetes更新。


[listing]
----
kubectl apply -f <updated-backend-file.yaml>
----
或者、您也可以執行下列命令來變更現有的「TridentBackendConfig」CR：

[listing]
----
kubectl edit tbc <tbc-name> -n trident
----
如果後端更新失敗、後端仍會繼續維持其最後已知的組態。您可以執行「kubecl Get tbc <tbc-name>-o yaml -n trident」或「kubecl描述tbc <tbc-name>-n trident」來檢視記錄以判斷原因。

識別並修正組態檔的問題之後、即可重新執行update命令。
