---
sidebar: sidebar 
permalink: trident-use/element.html 
keywords: trident backend, solidfire, netapp hci 
summary: 瞭解如何在安裝Astra Trident時建立及使用元素後端。 
---
= 設定NetApp HCI 一個不只是功能的SolidFire 後端
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


瞭解如何在安裝Astra Trident時建立及使用元素後端。

.您需要的產品
* 支援的儲存系統、可執行Element軟體。
* 提供給NetApp HCI / SolidFire叢集管理員或租戶使用者的認證、以管理磁碟區。
* 您所有的Kubernetes工作節點都應該安裝適當的iSCSI工具。請參閱 link:../trident-use/worker-node-prep.html["工作節點準備資訊"^]。


.您需要知道的資訊
「Poolidfire - san」儲存驅動程式支援兩種Volume模式：檔案和區塊。對於「檔案系統」磁碟區模式、Astra Trident會建立一個磁碟區並建立檔案系統。檔案系統類型由StorageClass指定。

[cols="5"]
|===
| 驅動程式 | 傳輸協定 | Volume模式 | 支援的存取模式 | 支援的檔案系統 


| 「olidfire - san」  a| 
iSCSI
 a| 
區塊
 a| 
rwo、ROX、rwx
 a| 
無檔案系統。原始區塊裝置。



| 「olidfire - san」  a| 
iSCSI
 a| 
區塊
 a| 
rwo、ROX、rwx
 a| 
無檔案系統。原始區塊裝置。



| 「olidfire - san」  a| 
iSCSI
 a| 
檔案系統
 a| 
Rwo、ROX
 a| 
《xfs》、《ext3》、《ext4》



| 「olidfire - san」  a| 
iSCSI
 a| 
檔案系統
 a| 
Rwo、ROX
 a| 
《xfs》、《ext3》、《ext4》

|===

NOTE: Astra Trident在做為增強型的csi資源配置程式時使用CHAP。如果您使用的是CHAP（這是「csi」的預設值）、則不需要進一步準備。建議將「UseCHAP」選項明確設定為搭配非「csi Trident」使用CHAP。否則請參閱 link:../trident-concepts/vol-access-groups.html["請按這裡"^]。


WARNING: Volume存取群組僅受Astra Trident的傳統非csi架構支援。當Astra Trident設定為以「csi」模式運作時、會使用CHAP。

如果未設定「存取群組」或「UseCHAP」、則適用下列其中一項規則：

* 如果偵測到預設的「Trident」存取群組、就會使用存取群組。
* 如果未偵測到存取群組、且Kubernetes版本為1.7或更新版本、則會使用CHAP。




== 後端組態選項

如需後端組態選項、請參閱下表：

[cols="3"]
|===
| 參數 | 說明 | 預設 


| 「分度」 |  | 永遠為1 


| 「torageDriverName」 | 儲存驅動程式名稱 | 永遠是「solidfire-san」 


| 「後端名稱」 | 自訂名稱或儲存後端 | 「S指_」+儲存設備（iSCSI）IP位址SolidFire 


| 端點 | MVIP、適用於SolidFire 採用租戶認證的不含用戶身分證明的叢集 |  


| 《VIP》 | 儲存設備（iSCSI）IP位址和連接埠 |  


| 《標籤》 | 套用到磁碟區的任意JSON-格式化標籤集。 | 「」 


| 《天王名稱》 | 要使用的租戶名稱（如果找不到、請建立） |  


| 《初始器IFACE》 | 將iSCSI流量限制在特定的主機介面 | 「預設」 


| 《UseCHAP》 | 使用CHAP驗證iSCSI | 是的 


| 《存取群組》 | 要使用的存取群組ID清單 | 尋找名為「Trident」的存取群組ID 


| 《類型》 | QoS規格 |  


| 《限制Volume大小》 | 如果要求的磁碟區大小高於此值、則資源配置失敗 | 「」（預設不強制執行） 


| 「DebugTraceFlags」 | 疑難排解時要使用的偵錯旗標。範例：｛"API"：假、「方法」：true｝ | null 
|===

WARNING: 除非您正在進行疑難排解並需要詳細的記錄傾印、否則請勿使用「debugTraceFlags」。


NOTE: 對於所有建立的磁碟區、Astra Trident會在儲存資源池上的所有標籤配置時、複製到備用儲存LUN。儲存管理員可以定義每個儲存資源池的標籤、並將儲存資源池中建立的所有磁碟區分組。這是根據後端組態中提供的一組可自訂標籤、方便區分磁碟區的方法。



== 範例1：的後端組態 `solidfire-san` 三種磁碟區類型的驅動程式

此範例顯示使用CHAP驗證的後端檔案、並建立具有特定QoS保證的三種Volume類型模型。您很可能會使用「IOPS」儲存類別參數來定義儲存類別、以使用每個類別。

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://<user>:<password>@<mvip>/json-rpc/8.0",
    "SVIP": "<svip>:3260",
    "TenantName": "<tenant>",
    "labels": {"k8scluster": "dev1", "backend": "dev1-element-cluster"},
    "UseCHAP": true,
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}
----


== 範例2：的後端與儲存類別組態 `solidfire-san` 驅動程式搭配虛擬儲存資源池

此範例顯示使用虛擬儲存資源池設定的後端定義檔案、以及參照回溯的StorageClass。

在下圖所示的範例後端定義檔中、會針對所有儲存資源池設定特定的預設值、將「type」設為Silver。虛擬儲存資源池是在「儲存區」區段中定義的。在此範例中、有些儲存資源池會設定自己的類型、有些資源池則會覆寫上述設定的預設值。

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://<user>:<password>@<mvip>/json-rpc/8.0",
    "SVIP": "<svip>:3260",
    "TenantName": "<tenant>",
    "UseCHAP": true,
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}],

    "type": "Silver",
    "labels":{"store":"solidfire", "k8scluster": "dev-1-cluster"},
    "region": "us-east-1",

    "storage": [
        {
            "labels":{"performance":"gold", "cost":"4"},
            "zone":"us-east-1a",
            "type":"Gold"
        },
        {
            "labels":{"performance":"silver", "cost":"3"},
            "zone":"us-east-1b",
            "type":"Silver"
        },
        {
            "labels":{"performance":"bronze", "cost":"2"},
            "zone":"us-east-1c",
            "type":"Bronze"
        },
        {
            "labels":{"performance":"silver", "cost":"1"},
            "zone":"us-east-1d"
        }
    ]
}
----
下列StorageClass定義係指上述虛擬儲存資源池。使用「parameters.selector`」欄位、每個StorageClass都會呼叫哪些虛擬資源池可用於裝載磁碟區。磁碟區將會在所選的虛擬資源池中定義各個層面。

第一個StorageClass（「Poolidfire gold-s4」）會對應至第一個虛擬儲存集區。這是唯一提供黃金級效能的「Volume Type QoS」（Volume Type QoS）。最後一個StorageClass（「Poolidfire Silver」）會呼叫任何提供銀級效能的儲存資源池。Astra Trident將決定選取哪個虛擬儲存資源池、並確保符合儲存需求。

[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-gold-four
provisioner: csi.trident.netapp.io
parameters:
  selector: "performance=gold; cost=4"
  fsType: "ext4"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-silver-three
provisioner: csi.trident.netapp.io
parameters:
  selector: "performance=silver; cost=3"
  fsType: "ext4"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-bronze-two
provisioner: csi.trident.netapp.io
parameters:
  selector: "performance=bronze; cost=2"
  fsType: "ext4"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-silver-one
provisioner: csi.trident.netapp.io
parameters:
  selector: "performance=silver; cost=1"
  fsType: "ext4"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: solidfire-silver
provisioner: csi.trident.netapp.io
parameters:
  selector: "performance=silver"
  fsType: "ext4"
----


== 如需詳細資訊、請參閱

* link:../trident-concepts/vol-access-groups.html["Volume存取群組"^]

