---
sidebar: sidebar 
permalink: trident-use/fcp.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes, worker node, iscsi, scsi, scsi over fc, fibre channel, fcp, kubernetes clusters, self-healing, healing. 
summary:  
---
= 光纖通道（ FC ）支援
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您現在可以搭配 Trident 使用光纖通道（ FC ）傳輸協定，在 ONTAP 系統上配置及管理儲存資源。

* SCSI over Fibre Channel （ FC ）是 Trident 24.10 版本的技術預覽功能。 *

Fibre Channel 是企業儲存環境中廣泛採用的一種傳輸協定，因為它具有高效能，可靠性和擴充性。它為儲存裝置提供強大且有效率的通訊通道，可快速且安全地傳輸資料。透過光纖通道使用 SCSI ，您可以運用現有的 SCSI 儲存基礎架構，同時享有光纖通道的高效能和長距離功能。它可整合儲存資源，並建立可擴充且有效率的儲存區域網路（ SAN ），以低延遲處理大量資料。

使用 FC 功能搭配 Trident ，您可以執行下列動作：

* 使用部署規格動態配置 PVC 。
* 擷取 Volume 快照，並從快照建立新的 Volume 。
* 複製現有的 FC-PVC 。
* 調整已部署磁碟區的大小。




== 先決條件

設定 FC 所需的網路和節點設定。



=== 網路設定

. 取得目標介面的 WWPN 。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap-cli//network-interface-show.html["網路介面顯示"^] 。
. 取得啟動器（主機）介面的 WWPN 。
+
請參閱對應的主機作業系統公用程式。

. 使用主機和目標的 WWPN 在 FC 交換器上設定分區。
+
如需詳細資訊，請參閱重新輸入交換器廠商文件。

+
如需詳細資訊，請參閱下列 ONTAP 文件：

+
** https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["Fibre Channel和FCoE分區總覽"^]
** https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html["設定 FC 擴大機、 FC-NVMe SAN 主機的方法"^]






=== 準備工作節點

Kubernetes叢集中的所有工作節點都必須能夠掛載您已為Pod配置的磁碟區。若要為 FC 準備工作節點，您必須安裝必要的工具。

.安裝 FC 工具
使用作業系統的命令來安裝FC工具。

* 當使用執行 RHEL / RedHat CoreOS 搭配 FC PV 的工作節點時，請在 StorageClass 中指定 `discard` mountOption 以執行內嵌空間回收。請參閱 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["RedHat文件"^]。


[role="tabbed-block"]
====
.RHEL 8以上
--
. 安裝下列系統套件：
+
[listing]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. 啟用多重路徑：
+
[listing]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 確保在"default"（錯誤）下"etc/multipath.conf"包含"fappe_multipaths no"。

. 確定 `multipathd`執行中：
+
[listing]
----
sudo systemctl enable --now multipathd
----


--
.Ubuntu
--
. 安裝下列系統套件：
+
[listing]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. 啟用多重路徑：
+
[listing]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 確保在"default"（錯誤）下"etc/multipath.conf"包含"fappe_multipaths no"。

. 確定 `multipath-tools`已啟用並正在執行：
+
[listing]
----
sudo systemctl status multipath-tools
----


--
====


== 建立後端組態

為驅動程式和 `fcp` sanType 建立 Trident 後端 `ontap-san`。

請參閱：

* link:..trident-use/ontap-san-prep.html["準備使用ONTAP 支援的SAN驅動程式來設定後端"]
* link:..trident-use/ontap-san-examples.html["SAN組態選項與範例ONTAP"^]


.FC 的後端組態範例
[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-san
spec:
  version: 1
  backendName: ontap-san-backend
  storageDriverName: ontap-san
  managementLIF: 10.0.0.1
  sanType: fcp
  svm: trident_svm
  credentials:
    name: backend-tbc-ontap-san-secret
----


== 建立儲存類別

如需詳細資訊、請參閱：

* link:..trident-docker/stor-config.html["儲存組態選項"^]


.儲存類別範例
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fcp-sc
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  storagePools: "ontap-san-backend:.*"
  fsType: "ext4"
allowVolumeExpansion: True
----