---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: 深入瞭解如何使用ONTAP 支援支援功能的SAN驅動程式來設定支援功能的後端。ONTAP 
---
= ONTAP SAN 驅動程式概觀
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
深入瞭解如何使用ONTAP 支援功能的功能和功能性SAN驅動程式來設定功能性的後端。ONTAP Cloud Volumes ONTAP



== ONTAP SAN 驅動程式詳細資料

Astra Trident 提供下列 SAN 儲存驅動程式、可與 ONTAP 叢集通訊。支援的存取模式包括： _ReadWriteOnce_ （ rwo ）、 _ReadOnlyMany （ ROX ）、 _ReadWriteMany （ rwx ）、 _ReadWriteOncePod （ RWOP_ ）。


IMPORTANT: 如果您使用 Astra Control 來保護、恢復和移動、請閱讀 <<Astra Control 驅動程式相容性>>。

[cols="2, 1, 1, 2, 2"]
|===
| 驅動程式 | 傳輸協定 | Volume模式 | 支援的存取模式 | 支援的檔案系統 


| 「ONTAP-SAN」  a| 
iSCSI
 a| 
區塊
 a| 
Rwo 、 ROX 、 rwx 、 RWOP
 a| 
無檔案系統；原始區塊裝置



| 「ONTAP-SAN」  a| 
iSCSI
 a| 
檔案系統
 a| 
RWO 、 RWOP

檔案系統磁碟區模式中無法使用 Rox 和 rwx 。
 a| 
《xfs》、《ext3》、《ext4》



| 「ONTAP-SAN」  a| 
NVMe / TCP

請參閱 <<NVMe / TCP 的其他考量事項>>。
 a| 
區塊
 a| 
Rwo 、 ROX 、 rwx 、 RWOP
 a| 
無檔案系統；原始區塊裝置



| 「ONTAP-SAN」  a| 
NVMe / TCP

請參閱 <<NVMe / TCP 的其他考量事項>>。
 a| 
檔案系統
 a| 
RWO 、 RWOP

檔案系統磁碟區模式中無法使用 Rox 和 rwx 。
 a| 
《xfs》、《ext3》、《ext4》



| 《ONTAP-san經濟》  a| 
iSCSI
 a| 
區塊
 a| 
Rwo 、 ROX 、 rwx 、 RWOP
 a| 
無檔案系統；原始區塊裝置



| 《ONTAP-san經濟》  a| 
iSCSI
 a| 
檔案系統
 a| 
RWO 、 RWOP

檔案系統磁碟區模式中無法使用 Rox 和 rwx 。
 a| 
《xfs》、《ext3》、《ext4》

|===


=== Astra Control 驅動程式相容性

Astra Control可為使用建立的磁碟區提供無縫保護、災難恢復和移動性（在Kubernetes叢集之間移動磁碟區） `ontap-nas`、 `ontap-nas-flexgroup`和 `ontap-san` 驅動程式：請參閱 link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Astra Control複寫先決條件"^] 以取得詳細資料。

[WARNING]
====
* 使用 `ontap-san-economy` 只有持續磁碟區使用量計數預期會高於 link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["支援的 ONTAP Volume 限制"^]。
* 使用 `ontap-nas-economy` 只有持續磁碟區使用量計數預期會高於 link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["支援的 ONTAP Volume 限制"^] 和 `ontap-san-economy` 無法使用驅動程式。
* 請勿使用 `ontap-nas-economy` 如果您預期需要資料保護、災難恢復或行動性、


====


== 使用者權限

Astra Trident希望以ONTAP 支援或SVM管理員的身分執行、通常是使用「admin」叢集使用者或「vsadmin」SVM使用者、或使用具有相同角色的不同名稱使用者。對於Amazon FSx for NetApp ONTAP 等部署、Astra Trident預期會使用ONTAP 叢集「fsxadmin」使用者或「vsadmin」SVM使用者、或是具有相同角色之不同名稱的使用者、來執行成一個或多個SVM管理員。「fsxadmin」使用者是叢集管理使用者的有限替代。


NOTE: 如果您使用「limitAggregateusage」參數、則需要叢集管理權限。使用Amazon FSx for NetApp ONTAP 支援Astra Trident時、「limitAggregateusage」參數無法搭配「vsadmin」和「fsxadmin」使用者帳戶使用。如果您指定此參數、組態作業將會失敗。

雖然可以在 ONTAP 中建立更具限制性的角色、讓 Trident 驅動程式可以使用、但我們不建議這樣做。Trident的大多數新版本都會呼叫額外的API、而這些API必須納入考量、使升級變得困難且容易出錯。



== NVMe / TCP 的其他考量事項

Astra Trident 支援使用的非揮發性記憶體高速（ NVMe ）傳輸協定 `ontap-san` 驅動程式包括：

* IPv6
* NVMe 磁碟區的快照和複本
* 調整 NVMe 磁碟區大小
* 匯入 Astra Trident 外部建立的 NVMe Volume 、以便 Astra Trident 管理其生命週期
* NVMe 原生多重路徑
* K8s 節點正常或不正常關機（ 23.10 ）


Astra Trident 不支援：

* NVMe 原生支援的 DH-HMAC-CHAP
* 裝置對應工具（ DM ）多重路徑
* LUKS 加密

