---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 使用 Trident 搭配 Amazon FSX for NetApp ONTAP 、您可以確保在 Amazon Elastic Kubernetes Service （ EKS ）中執行的 Kubernetes 叢集可以佈建由 ONTAP 支援的區塊和檔案持續性磁碟區。 
---
= 安裝Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 簡化了 Kubernetes 中適用於 NetApp ONTAP 儲存管理的 Amazon FSX 、讓開發人員和管理員能夠專注於應用程式部署。

您可以使用下列其中一種方法來安裝 Trident ：

* 掌舵
* EKS 附加元件


如果您想要使用快照功能，請安裝 CSI Snapshot 控制器附加元件。如需詳細資訊、請參閱 link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["啟用 CSI Volume 的快照功能"^] 。



== 透過 helm 安裝 Trident

[role="tabbed-block"]
====
.Pod 身份
--
. 新增Trident Helm儲存庫：
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 使用下列範例安裝 Trident：
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
您可以使用 `helm list`命令檢閱安裝詳細資料，例如名稱，命名空間，圖表，狀態，應用程式版本和修訂版編號。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.服務帳戶協會 (IRSA)
--
. 新增Trident Helm儲存庫：
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 設定「雲端提供者」和「雲端身分」的值：
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
您可以使用 `helm list`命令檢閱安裝詳細資料，例如名稱，命名空間，圖表，狀態，應用程式版本和修訂版編號。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
如果您打算使用 iSCSI，請確保在用戶端電腦上啟用了 iSCSI。如果您使用的是 AL2023 工作節點作業系統，則可以透過在 helm 安裝中新增 node prep 參數來自動安裝 iSCSI 用戶端：

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== 透過 EKS 附加元件安裝 Trident

Trident EKS 附加元件包含最新的安全性修補程式、錯誤修正、並經過 AWS 驗證、可與 Amazon EKS 搭配使用。EKS 附加元件可讓您持續確保 Amazon EKS 叢集安全穩定、並減少安裝、設定及更新附加元件所需的工作量。



=== 先決條件

在設定 AWS EKS 的 Trident 附加元件之前、請確定您具有下列項目：

* 具有附加訂閱的 Amazon EKS 叢集帳戶
* AWS 對 AWS 市場的權限：
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* AMI 類型： Amazon Linux 2 （ AL2_x86_64 ）或 Amazon Linux 2 ARM （ AL2_ARM_64 ）
* 節點類型： AMD 或 ARM
* 現有的 Amazon FSX for NetApp ONTAP 檔案系統




=== 啟用 AWS 的 Trident 附加元件

[role="tabbed-block"]
====
.管理主控台
--
. 開啟 Amazon EKS 主控台： https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左側導航窗格中，選擇 *Clusters* 。
. 選取您要設定 NetApp Trident CSI 附加元件的叢集名稱。
. 選取 * 附加元件 * ，然後選取 * 取得更多附加元件 * 。
. 請依照以下步驟選擇附加元件：
+
.. 向下捲動至 *AWS Marketplace 附加元件* 部分，然後在搜尋框中輸入 *「Trident」*。
.. 選取 NetApp 的 Trident 方塊右上角的核取方塊。
.. 選擇*下一步*。


. 在 * 設定選取的附加元件 * 設定頁面上、執行下列步驟：
+
.. 選擇您要使用的 * 版本 * 。
.. 如果您使用 IRSA 驗證，請確保設定可選組態設定中可用的設定值：
+
*** 選擇您要使用的 * 版本 * 。
*** 依照 *附加元件配置模式*，將 *配置值* 部分中的 *configurationValues* 參數設定為您在上一個步驟中建立的角色 ARN（值應採用以下格式）：




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
如果您為衝突解決方法選取「覆寫」、則現有附加元件的一或多個設定可以使用 Amazon EKS 附加元件設定覆寫。如果您未啟用此選項、且與現有設定發生衝突、則作業將會失敗。您可以使用產生的錯誤訊息來疑難排解衝突。選取此選項之前、請確定 Amazon EKS 附加元件不會管理您需要自行管理的設定。

. 選擇 * 下一步 * 。
. 在 * 檢閱及新增 * 頁面上、選擇 * 建立 * 。
+
附加元件安裝完成後、您會看到已安裝的附加元件。



--
.AWS CLI
--
*1.創建 `add-on.json`文件*：

*對於 Pod Identity，請使用以下格式*：

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*對於 IRSA 驗證，請使用以下格式*：

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: 取代 `<role ARN>`前一步驟所建立角色的 ARN 。

*2.安裝 Trident EKS 外掛程式。 *

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
下列範例命令會安裝 Trident EKS 附加元件：

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== 更新 Trident EKS 附加元件

[role="tabbed-block"]
====
.管理主控台
--
. 打開 Amazon EKS 控制檯 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左側導航窗格中，選擇 *Clusters* 。
. 選取您要更新 NetApp Trident CSI 附加元件的叢集名稱。
. 選取 * 附加元件 * 索引標籤。
. 選取 * Trident by NetApp * ，然後選取 * 編輯 * 。
. 在 * Configure Trident by NetApp * 頁面上、執行下列步驟：
+
.. 選擇您要使用的 * 版本 * 。
.. 展開 * 選用組態設定 * ，並視需要修改。
.. 選取*儲存變更*。




--
.AWS CLI
--
下列範例更新 EKS 附加元件：

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* 檢查 FSxN Trident CSI 附加元件的目前版本。以叢集名稱取代 `my-cluster`。
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
* 輸出範例： *



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* 將附加元件更新至上一個步驟輸出中可用更新所傳回的版本。
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


如果您移除此 `--force` 選項、且任何 Amazon EKS 附加元件設定與您現有的設定發生衝突、則更新 Amazon EKS 附加元件會失敗；您會收到錯誤訊息、協助您解決衝突。在指定此選項之前、請確定 Amazon EKS 附加元件不會管理您需要管理的設定、因為這些設定會以此選項覆寫。如需此設定的其他選項的詳細資訊，請參閱 link:https://eksctl.io/usage/addons/["附加元件"]。如需 Amazon EKS Kubernetes 現場管理的詳細資訊、請參閱 link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Kubernetes 現場管理"]。

--
====


=== 解除安裝 / 移除 Trident EKS 附加元件

您有兩種移除 Amazon EKS 附加元件的選項：

* * 保留叢集上的附加軟體 * –此選項會移除 Amazon EKS 對任何設定的管理。它也會移除 Amazon EKS 通知您更新的功能、並在您啟動更新後自動更新 Amazon EKS 附加元件。不過、它會保留叢集上的附加軟體。此選項可讓附加元件成為自我管理的安裝、而非 Amazon EKS 附加元件。有了這個選項、附加元件就不會停機。保留 `--preserve` 命令中的選項以保留附加元件。
* * 從叢集完全移除附加軟體 * – NetApp 建議您只有在叢集上沒有任何相關資源的情況下，才從叢集移除 Amazon EKS 附加元件。從命令中移除 `--preserve` 選項 `delete` 以移除附加元件。



NOTE: 如果附加元件有相關的 IAM 帳戶、則不會移除 IAM 帳戶。

[role="tabbed-block"]
====
.管理主控台
--
. 開啟 Amazon EKS 主控台： https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左導覽窗格中，選取 * 叢集 * 。
. 選取您要移除 NetApp Trident CSI 附加元件的叢集名稱。
. 選擇 *Add-ons* 標籤，然後選擇 Trident by NetApp * 。 *
. 選擇*移除*。
. 在 * 移除 NetApp_trident 操作員確認 * 對話方塊中、執行下列步驟：
+
.. 如果您想要 Amazon EKS 停止管理附加元件的設定、請選取 * 保留在叢集 * 上。如果您想要保留叢集上的附加軟體、以便自行管理附加元件的所有設定、請執行此動作。
.. 輸入 *NetApp_trident － operer* 。
.. 選擇*移除*。




--
.AWS CLI
--
以叢集名稱取代 `my-cluster` 、然後執行下列命令。

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
下列命令會解除安裝 Trident EKS 附加元件：

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====