---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 使用 Trident 搭配 Amazon FSX for NetApp ONTAP 、您可以確保在 Amazon Elastic Kubernetes Service （ EKS ）中執行的 Kubernetes 叢集可以佈建由 ONTAP 支援的區塊和檔案持續性磁碟區。 
---
= 搭配 Amazon FSX for NetApp ONTAP 使用 Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 產品"^] 是一項完全託管的 AWS 服務，可執行由 NetApp ONTAP 儲存作業系統提供支援的檔案系統。它提供 ONTAP 的功能、效能和管理能力，同時兼具 AWS 的可擴充性和營運簡易性。檔案系統是 Amazon FSx 中的主要資源，類似於內部部署的 ONTAP 叢集。每個檔案系統包含一個或多個儲存虛擬機器（SVM），每個 SVM 包含一個或多個用於儲存檔案和目錄的磁碟區。這種整合使得在 Amazon Elastic Kubernetes Service（EKS）中執行的 Kubernetes 叢集能夠為區塊和檔案工作負載佈建由 ONTAP 支援的持續磁碟區。



== 需求

除了link:../trident-get-started/requirements.html["Trident 需求"]、若要將適用於 ONTAP 的 FSX 與 Trident 整合、您還需要：

* 現有的Amazon EKS叢集或自行管理的Kubernetes叢集、已安裝「kubecll」。
* 可從叢集工作節點存取的現有 Amazon FSX for NetApp ONTAP 檔案系統和儲存虛擬機器（ SVM ）。
* 已準備好的工作節點 link:worker-node-prep.html["NFS或iSCSI"]。
+

NOTE: 請務必遵循Amazon Linux和Ubuntu所需的節點準備步驟 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Amazon機器映像"^] （AMis）、視您的EKS AMI類型而定。





== 考量

* SMB Volume：
+
** 使用支援SMB磁碟區 `ontap-nas` 僅限驅動程式。
** Trident EKS 附加元件不支援 SMB Volume 。
** Trident 僅支援掛載至 Windows 節點上執行的 Pod 的 SMB 磁碟區。如 link:../trident-use/trident-fsx-storage-backend.html#prepare-to-provision-smb-volumes["準備配置SMB磁碟區"] 需詳細資訊、請參閱。


* 在 Trident 24.02 之前、在已啟用自動備份的 Amazon FSX 檔案系統上建立的磁碟區、無法由 Trident 刪除。若要在 Trident 24.02 或更新版本中避免此問題、請在 AWS FSX for ONTAP 的後端組態檔案中指定 `fsxFilesystemID`、 AWS `apiRegion`、 AWS `apikey` 和 AWS `secretKey` 。
+

NOTE: 如果您要將 IAM 角色指定給 Trident 、則可以省略將、 `apiKey`和 `secretKey`欄位明確指定 `apiRegion`給 Trident 。如需詳細資訊、請 link:../trident-use/trident-fsx-examples.html["FSX提供ONTAP 各種組態選項和範例"]參閱。





=== 同時使用Trident SAN/iSCSI 和 EBS-CSI 驅動程式

如果您打算將 ontap-san 驅動程式（例如 iSCSI）與 AWS（EKS、ROSA、EC2 或任何其他執行個體）一起使用，則節點上所需的多路徑配置可能會與 Amazon Elastic Block Store (EBS) CSI 驅動程式衝突。為了確保多路徑功能不會幹擾同一節點上的 EBS 磁碟，您需要在多路徑設定中排除 EBS。這個例子展示了 `multipath.conf`包含所需Trident設定的文件，同時將 EBS 磁碟排除在多路徑之外：

[listing]
----
defaults {
    find_multipaths no
}
blacklist {
    device {
        vendor "NVME"
        product "Amazon Elastic Block Store"
    }
}
----


== 驗證

Trident 提供兩種驗證模式。

* 認證型（建議）：在 AWS Secrets Manager 中安全地儲存認證。您可以將使用者用於檔案系統、或是使用 `fsxadmin` `vsadmin` 為 SVM 設定的使用者。
+

WARNING: Trident 應以 SVM 使用者或具有相同角色之不同名稱的使用者身分執行 `vsadmin`。Amazon FSX for NetApp ONTAP 的 `fsxadmin`使用者僅能有限地取代 ONTAP `admin` 叢集使用者。我們強烈建議搭配 Trident 使用 `vsadmin`。

* 憑證型： Trident 將使用 SVM 上安裝的憑證、與 FSX 檔案系統上的 SVM 通訊。


如需啟用驗證的詳細資訊、請參閱您的驅動程式類型驗證：

* link:ontap-nas-prep.html["ASNAS驗證ONTAP"]
* link:ontap-san-prep.html["支援SAN驗證ONTAP"]




== 已測試的 Amazon Machine 映像（ Amis ）

EKS 叢集支援各種作業系統，但 AWS 已針對容器和 EKS 最佳化某些 Amazon Machine 映像（ Amis ）。以下 AMI 已通過 NetApp Trident 25.02 測試。

|===


| Ami | NAS | NAS 經濟效益 | iSCSI | iSCSI經濟型 


| AL2023_x86_64_STANDARD | 是的 | 是的 | 是的 | 是的 


| AL2_x86_64 | 是的 | 是的 | 是* | 是* 


| BOTTLEROCKET_x86_64 | 是 ** | 是的 | 不適用 | 不適用 


| AL2023_ARM_64_STANDARD | 是的 | 是的 | 是的 | 是的 


| AL2_ARM_64 | 是的 | 是的 | 是* | 是* 


| BOTTLEROCKET_ARM_64 | 是 ** | 是的 | 不適用 | 不適用 
|===
* * 如果不重新啟動節點，則無法刪除 PV
* ** 不適用於Trident版本 25.02 的 NFSv3。



NOTE: 如果此處未列出您想要的 AMI ，並不表示不支援，只是表示尚未測試。此清單可作為已知可運行的 AMI 的指南。

* 使用 * 執行的測試：

* EKS版本：1.32
* 安裝方法：Helm 25.06 和 AWS 附加元件 25.06
* 對於 NAS ， NFSv3 和 NFSv4.1 都已經過測試。
* 僅針對 SAN 進行 iSCSI 測試，非 NVMe 型。


* 已執行的測試 * ：

* 建立：儲存類別， PVC ， Pod
* 刪除： Pod ， PVC （一般， qtree /LUN –經濟， NAS 搭配 AWS 備份）




== 如需詳細資訊、請參閱

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 的支援文件"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["Amazon FSX for NetApp ONTAP 的部落格文章"^]

