= 還原和容錯移轉作業期間的命名空間註釋和標籤
:allow-uri-read: 




== 還原和容錯移轉作業期間的命名空間註釋和標籤

在還原和容錯移轉作業期間，目的地命名空間中的標籤和註釋會與來源命名空間中的標籤和註釋相符。會新增來源命名空間中不存在的標籤或註釋，並覆寫已存在的任何標籤或註釋，以符合來源命名空間的值。只存在於目的地命名空間上的標籤或註釋會保持不變。


NOTE: 如果您使用 Red Hat OpenShift，請務必注意命名空間註解在 OpenShift 環境中的重要角色。命名空間註解可確保復原的 pod 遵守 OpenShift 安全性情境約束 (SCC) 定義的適當權限和安全性配置，並且可以存取磁碟區而不會出現權限問題。欲了解更多信息，請參閱link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["OpenShift 安全性內容限制文件"^]。

您可以在執行還原或容錯移轉作業之前，先設定 Kubernetes 環境變數，以避免覆寫目的地命名空間中的特定註釋 `RESTORE_SKIP_NAMESPACE_ANNOTATIONS`。例如：

[source, console]
----
helm upgrade trident-protect --set restoreSkipNamespaceAnnotations=<annotation_key_to_skip_1>,<annotation_key_to_skip_2> --reuse-values
----

NOTE: 執行復原或故障轉移操作時，任何命名空間註解和標籤都將生效。 `restoreSkipNamespaceAnnotations` 和 `restoreSkipNamespaceLabels` 不參與恢復或故障轉移操作。確保在初始 Helm 安裝期間配置這些設定。欲了解更多信息，請參閱 link:../trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["設定其他Trident保護 Helm Chart 設定"]。

如果您使用帶有標誌的 Helm 來安裝來源應用程式 `--create-namespace`，則會對標籤機碼給予特殊處理 `name`。在還原或容錯移轉程序期間， Trident Protect 會將此標籤複製到目的地命名空間，但如果來源的值符合來源命名空間，則會將值更新到目的地命名空間值。如果此值與來源命名空間不相符，則會將其複製到目的地命名空間，而不會有任何變更。



=== 範例

以下範例提供來源和目的地命名空間，每個命名空間都有不同的註釋和標籤。您可以查看作業前後目的地命名空間的狀態，以及註釋和標籤在目的地命名空間中的組合或覆寫方式。



==== 還原或容錯移轉作業之前

下表說明還原或容錯移轉作業之前的範例來源和目的地命名空間狀態：

[cols="1,2a,2a"]
|===
| 命名空間 | 註釋 | 標籤 


| 命名空間 nS-1 （來源）  a| 
* annotation.one / 機碼：「 updatedvalue 」
* annotation.b2/key ：「 true 」

 a| 
* 環境 = 正式作業
* Compliance = HIPAA
* NAME=ns-1




| 命名空間 nS-2 （目的地）  a| 
* annotation.one / 機碼：「 true 」
* annotation.the/key ：「 FALSE 」

 a| 
* role = 資料庫


|===


==== 還原作業之後

下表說明還原或容錯移轉作業之後範例目的地命名空間的狀態。某些金鑰已新增，部分已覆寫， `name`標籤已更新以符合目的地命名空間：

[cols="1,2a,2a"]
|===
| 命名空間 | 註釋 | 標籤 


| 命名空間 nS-2 （目的地）  a| 
* annotation.one / 機碼：「 updatedvalue 」
* annotation.b2/key ：「 true 」
* annotation.the/key ：「 FALSE 」

 a| 
* NAME=nS-2
* Compliance = HIPAA
* 環境 = 正式作業
* role = 資料庫


|===