= 
:allow-uri-read: 


. （ _Optional_ ）如果您只需要選取應用程式的某些資源來還原，請新增篩選功能，以包含或排除標記有特定標籤的資源：
+

NOTE: Trident Protect 會自動選取部分資源，因為這些資源與您選取的資源之間的關係。例如，如果您選取持續磁碟區宣告資源，而且該資源有相關聯的 Pod ，則 Trident Protect 也會還原相關聯的 Pod 。

+
** *resourceFilter.resourceSelectionCriteria* ：（篩選所需）使用 `Include`或包含或 `Exclude`排除在 resourceMatchers 中定義的資源。新增下列資源配置工具參數、以定義要納入或排除的資源：
+
*** *resourceFilter.resourceMatchers* ：一組 resourceMatcher 物件。如果您在此陣列中定義多個元素，它們會比對為 OR 作業，而每個元素（群組，種類，版本）內的欄位會比對為 AND 作業。
+
**** *resourceMatchers[].group* ：（ _Optional_ ）要篩選的資源群組。
**** *resourceMatchers[].cher* ：（ _Optional_ ）要篩選的資源種類。
**** *resourceMatchers[].version* ：（ _Optional_ ）要篩選的資源版本。
**** 要篩選之資源的 Kubernetes metadata.name 欄位中的 * resourceMatchers[].names* ：（ _Optional_ ）名稱。
**** 要篩選之資源的 Kubernetes metadata.name 欄位中的 * resourceMatchers[].names* ：（ _Optional_ ）命名空間。
**** 資源的 Kubernetes metadata.name 欄位中的 *resourceMatchers[].labelSelectors * ：（ _Optional_ ） Label 選取器字串，如中所定義 https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["Kubernetes文件"^]。例如 `"trident.netapp.io/os=linux"`：。
+
例如：

+
[source, yaml]
----
spec:
  resourceFilter:
    resourceSelectionCriteria: "Include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
----







