---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy.html 
keywords: deploy, astra trident, methods, operator, tridentctl, helm, tanzu, vmware 
summary: '您可以使用Trident運算子（手動或使用Helm）或搭配安裝Astra Trident `tridentctl`。本主題提供重要資訊、協助您選擇正確的安裝程序。' 
---
= 瞭解Astra Trident安裝
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了確保Astra Trident可安裝在各種環境和組織中、NetApp提供多種安裝選項。您可以使用Trident運算子（手動或使用Helm）或搭配安裝Astra Trident `tridentctl`。本主題提供重要資訊、協助您選擇正確的安裝程序。



== Astra Trident 23.04 的重要資訊

*您必須閱讀下列有關Astra Trident的重要資訊。*

.關於Astra Trid-功能 的資訊</strong> <strong>
[%collapsible%open]
====
* Kubernetes 1.27 現在支援 Trident 。升級Kubernetes之前先升級Trident。
* Astra Trident在SAN環境中嚴格執行多重路徑組態的使用、建議的值為 `find_multipaths: no` 在多重路徑.conf檔案中。
+
使用非多重路徑組態或使用 `find_multipaths: yes` 或 `find_multipaths: smart` 多重路徑.conf檔案中的值會導致掛載失敗。Trident建議使用 `find_multipaths: no` 自21.07版本以來。



====


== 開始之前

無論安裝路徑為何、您都必須具備：

* 對執行支援版本Kubernetes及啟用功能需求的Kubernetes叢集擁有完整權限。檢閱 link:requirements.html["需求"] 以取得詳細資料。
* 存取支援的NetApp儲存系統。
* 能夠從所有Kubernetes工作節點掛載磁碟區。
* Linux主機 `kubectl` （或 `oc`（如果您使用OpenShift）已安裝並設定為管理您要使用的Kubernetes叢集。
* 。 `KUBECONFIG` 環境變數設定為指向Kubernetes叢集組態。
* 如果您使用Kubernetes搭配Docker Enterprise、 https://docs.docker.com/ee/ucp/user-access/cli/["請依照他們的步驟啟用CLI存取"^]。



TIP: 如果您尚未熟悉 link:../trident-concepts/intro.html["基本概念"^]現在正是這麼做的好時機。



== 選擇您的安裝方法

選取最適合您的安裝方法。您也應該檢閱的考量事項 link:kubernetes-deploy.html#move-between-installation-methods["在方法之間移動"] 做出決定之前。



=== 使用Trident運算子

無論是手動部署或使用Helm、Trident營運者都是簡化安裝及動態管理Astra Trident資源的絕佳方式。您甚至可以 link:../trident-get-started/kubernetes-customize-deploy.html["自訂您的Trident營運者部署"] 使用中的屬性 `TridentOrchestrator` 自訂資源（CR）。

使用Trident營運者的好處包括：

.不只是個Trident物件、更是個可說是個可說是個地方</strong> <strong>
[%collapsible]
====
Trident運算子會自動為Kubernetes版本建立下列物件。

* 營運者服務帳戶
* 叢集角色和叢集角色繫結至服務帳戶
* 專屬的PodSecurity原則（適用於Kubernetes 1.25及更早版本）
* 營運者本身


====
.還原功能的功能</strong> <strong>
[%collapsible]
====
營運者會監控Astra Trident安裝、並主動採取措施來處理問題、例如刪除部署或意外修改部署。答 `trident-operator-<generated-id>` 建立Pod以建立關聯 `TridentOrchestrator` 含Astra Trident安裝的CR。如此可確保叢集中只有一個Astra Trident執行個體、並控制其設定、確保安裝功能強大。當對安裝進行變更（例如刪除部署或節點取消設定）時、操作員會分別識別並修正這些變更。

====
.更新至現有安裝的更新功能</strong> <strong>
[%collapsible]
====
您可以輕鬆地與營運者一起更新現有的部署。您只需要編輯 `TridentOrchestrator` 以更新安裝。

例如、假設您需要啟用Astra Trident來產生偵錯記錄的案例。若要這麼做、請修補您的 `TridentOrchestrator` 以設定 `spec.debug` 至 `true`：

[listing]
----
kubectl patch torc <trident-orchestrator-name> -n trident --type=merge -p '{"spec":{"debug":true}}'
----
更新「TridentOrchestrator」之後、營運者會處理更新並修補現有安裝。這可能會觸發建立新的Pod、以據此修改安裝。

====
.支援升級功能的不一樣之處</strong> <strong>
[%collapsible]
====
當叢集的Kubernetes版本升級至支援的版本時、營運者會自動更新現有的Astra Trident安裝、並加以變更、以確保其符合Kubernetes版本的要求。


NOTE: 如果叢集升級至不受支援的版本、則操作員將無法安裝Astra Trident。如果操作員已安裝Astra Trident、則會顯示警告、指出Astra Trident安裝在不受支援的Kubernetes版本上。

====
.使用BlueXP（前身為Cloud Manager）進行叢集管理</strong> <strong>
[%collapsible]
====
與 link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/concept-kubernetes.html["使用BlueXP的Astra Trident"^]、您可以升級至最新版的Astra Trident、新增及管理儲存類別、並將其連線至工作環境、以及使用Cloud Backup Service NetApp備份持續的Volume。BlueXP支援使用Trident操作者手動或使用Helm進行Astra Trident部署。

====


=== 使用 `tridentctl`

如果您現有的部署必須升級、或是想要高度自訂部署、您應該考慮 。這是部署Astra Trident的傳統方法。

您可以  以產生Trident資源的資訊清單。這包括部署、取消程式集、服務帳戶、以及Astra Trident在安裝過程中所建立的叢集角色。


NOTE: 從22.04版開始、每次安裝Astra Trident時、AES金鑰就不會再重新產生。在這個版本中、Astra Trident會安裝一個新的秘密物件、並在安裝過程中持續存在。這表示、 `tridentctl` 在22.04中可以解除安裝舊版Trident、但舊版無法解除安裝22.04安裝。選取適當的安裝方法_。



== 選擇安裝模式

根據組織所需的安裝模式_（標準、離線或遠端）來判斷您的部署程序。

[role="tabbed-block"]
====
.標準安裝
--
這是安裝Astra Trident最簡單的方法、適用於大多數不受網路限制的環境。標準安裝模式使用預設登錄來儲存所需的Trident (`docker.io`）和csi (`registry.k8s.io`）影像。

使用標準模式時、Astra Trident安裝程式會：

* 透過網際網路擷取容器映像
* 在Kubernetes叢集中的所有合格節點上建立部署或節點取消設定、以執行Astra Trident Pod


--
.離線安裝
--
在無線或安全的位置可能需要離線安裝模式。在此案例中、您可以建立單一私有、鏡射的登錄或兩個鏡射登錄、以儲存所需的Trident和csi映像。


NOTE: 無論您的登錄組態為何、都必須將csi映像存放在單一登錄中。

--
.遠端安裝
--
以下是遠端安裝程序的高階概觀：

* 在遠端機器上部署適當版本的「kubecll」、以便部署Astra Trident。
* 從Kubernetes叢集複製組態檔、然後在遠端機器上設定「KUBECCONFIG」環境變數。
* 啟動「kubectl Get nodes」命令、確認您可以連線至所需的Kubernetes叢集。
* 使用標準安裝步驟、從遠端機器完成部署。


--
====


== 根據您的方法和模式選取程序

做出決策後、請選擇適當的程序。

[cols="2"]
|===
| 方法 | 安裝模式 


| Trident運算子（手動）  a| 
link:kubernetes-deploy-operator.html["標準安裝"]

link:kubernetes-deploy-operator-mirror.html["離線安裝"]



| Trident運算子（Helm）  a| 
link:kubernetes-deploy-helm.html["標準安裝"]

link:kubernetes-deploy-helm-mirror.html["離線安裝"]



| `tridentctl`  a| 
link:kubernetes-deploy-tridentctl.html["標準或離線安裝"]

|===


== 在安裝方法之間移動

您可以決定變更安裝方法。在執行此操作之前、請先考慮下列事項：

* 安裝及解除安裝Astra Trident時、請務必使用相同的方法。如果您已部署 `tridentctl`、您應該使用適當版本的 `tridentctl` 二進位以解除安裝Astra Trident。同樣地、如果您是與操作員一起部署、則應該編輯 `TridentOrchestrator` 並設定 `spec.uninstall=true` 解除安裝Astra Trident。
* 如果您想要移除並改用以營運者為基礎的部署 `tridentctl` 若要部署Astra Trident、您應該先編輯 `TridentOrchestrator` 並設定 `spec.uninstall=true` 解除安裝Astra Trident。然後刪除 `TridentOrchestrator` 以及營運者部署。然後您可以使用安裝 `tridentctl`。
* 如果您有手動的操作員型部署、而且想要使用以Helm為基礎的Trident操作員部署、您應該先手動解除安裝操作員、然後再執行Helm安裝。如此一來、Helm就能部署具有所需標籤和註釋的Trident運算子。如果您不這麼做、則Helm型Trident營運者部署將會失敗、並顯示標籤驗證錯誤和註釋驗證錯誤。如果您有 `tridentctl`根據部署、您可以使用以Helm為基礎的部署、而不會發生問題。




== 其他已知組態選項

在VMware Tanzu產品組合產品上安裝Astra Trident時：

* 叢集必須支援特殊權限的工作負載。
* 「-kubelet-dir」旗標應設定為kubelet目錄的位置。依預設、這是「/var/vcap/data/kubelet」。
+
使用「-kubelet-dir」指定kubelet位置、已知適用於Trident運算子、Helm及「tridentctl」部署。


