---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, astra trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: 您可以部署Trident運算子、並使用Helm安裝Astra Trident。此程序適用於將Astra Trident所需的容器映像儲存在私有登錄中的安裝。 
---
= 使用Helm部署Trident運算子（離線模式）
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以部署Trident運算子、並使用Helm安裝Astra Trident。此程序適用於將Astra Trident所需的容器映像儲存在私有登錄中的安裝。如果您沒有私有映像登錄、請使用 link:kubernetes-deploy-helm.html["標準部署程序"]。



== Astra Trident的重要資訊23.01

*您必須閱讀下列有關Astra Trident的重要資訊。*

.關於Astra Trid-功能 的資訊</strong> <strong>
[%collapsible%open]
====
* Kubernetes 1.26現在已在Trident中受到支援。升級Kubernetes之前先升級Trident。
* Astra Trident在SAN環境中嚴格執行多重路徑組態的使用、建議的值為 `find_multipaths: no` 在多重路徑.conf檔案中。
+
使用非多重路徑組態或使用 `find_multipaths: yes` 或 `find_multipaths: smart` 多重路徑.conf檔案中的值會導致掛載失敗。Trident建議使用 `find_multipaths: no` 自21.07版本以來。



====


== 部署Trident操作員、並使用Helm安裝Astra Trident

使用Trident link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["掌舵表"^] 您可以部署Trident運算子、並在單一步驟中安裝Trident。

檢閱 link:../trident-get-started/kubernetes-deploy.html["安裝總覽"] 為了確保您符合安裝先決條件、並為您的環境選擇正確的安裝選項。

.開始之前
此外 link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["部署先決條件"] 您的需求 link:https://v3.helm.sh/["Helm版本3"^]。

.步驟
. 新增Astra Trident Helm儲存庫：
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 使用 `helm install` 並指定部署和映像登錄位置的名稱、如下列範例所示。在範例中、 `23.01.0` 是您要安裝的Astra Trident版本。
+
[role="tabbed-block"]
====
.Trident和csi映像位於單一登錄中
--
[listing]
----
helm install <name> netapp-trident/trident-operator --version 23.01.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace>
----
--
.不同登錄中的Trident和csi映像
--
您必須附加 `sig-storage` 至 `imageRegistry` 使用不同的登錄位置。

[listing]
----
helm install <name> netapp-trident/trident-operator --version 23.01.0 --set imageRegistry=<your-registry>/sig-storage --set operatorImage=<your-registry>/netapp/trident-operator:23.01.0 --set tridentAutosupportImage=<your-registry>/netapp/trident-autosupport:23.01 --set tridentImage=<your-registry>/netapp/trident:23.01.0 --create-namespace --namespace <trident-namespace>
----
--
====
+

NOTE: 如果您已經為Trident建立命名空間、則「-cree-namespacre」參數不會建立其他命名空間。



您可以使用 `helm list` 若要檢閱安裝詳細資料、例如名稱、命名空間、圖表、狀態、應用程式版本、和修訂編號。



== 在安裝期間傳遞組態資料

安裝期間有兩種傳遞組態資料的方法：

[cols="2"]
|===
| 選項 | 說明 


| `--values` （或 `-f`）  a| 
指定具有覆寫的Yaml檔案。這可以多次指定、最右邊的檔案會優先。



| `--set`  a| 
在命令列上指定置換。

|===
例如、變更的預設值 `debug`請執行下列步驟 `--set` 命令位置 `23.01.0` 您要安裝的Astra Trident版本：

[listing]
----
helm install <name> netapp-trident/trident-operator --version 23.01.0  --create-namespace --namespace --set tridentDebug=true
----

NOTE: Helm圖表中的「values.yaml」檔案提供金鑰清單及其預設值。



== 下一步

現在您可以了 link:kubernetes-postdeployment.html["建立後端和儲存類別、配置磁碟區、並將磁碟區掛載到Pod中"]。
