---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: Trident運算子可讓您使用「TridentOrchestrator」規格中的屬性、自訂Astra Trident的安裝方式。 
---
= 自訂Trident操作員安裝
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident運算子可讓您使用中的屬性來自訂Astra Trident安裝 `TridentOrchestrator` 規格如果您想要自訂安裝內容以外的內容 `TridentOrchestrator` 引數允許、請考慮使用 `tridentctl` 產生自訂的 YAML 資訊清單、以視需要進行修改。



== 瞭解控制器 Pod 和節點 Pod

Astra Trident 會以單一控制器 Pod 的形式執行、並在叢集中的每個工作節點上提供節點 Pod 。節點 Pod 必須在任何想要裝載 Astra Trident Volume 的主機上執行。

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["節點選取器"^] 和 link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["容忍和污染"^] 用於限制 Pod 在特定或偏好的節點上執行。使用「 ControllerPlugin' 」和 `NodePlugin`，您可以指定限制和置換。

* 控制器外掛程式可處理磁碟區資源配置與管理、例如快照和調整大小。
* 節點外掛程式會處理將儲存設備附加至節點的問題。




== 組態選項


WARNING: `spec.namespace` 在中指定 `TridentOrchestrator` 表示 Astra Trident 安裝的命名空間。此參數*無法在安裝Astra Trident之後更新*。嘗試這麼做會導致 `TridentOrchestrator` 要變更為的狀態 `Failed`。Astra Trident不打算跨命名空間移轉。

本表詳細說明 `TridentOrchestrator` 屬性。

[cols="3"]
|===
| 參數 | 說明 | 預設 


| 命名空間 | 用於安裝Astra Trident的命名空間 | "預設" 


| 「Debug」 | 啟用Astra Trident的偵錯功能 | 錯 


| `windows` | 設定為 `true` 可在Windows工作節點上安裝。 | 錯 


| 《IPv6》 | 透過IPv6安裝Astra Trident | 錯 


| 「k8stimeout」 | Kubernetes作業逾時 | 30秒 


| 「ilenceAutoSupport」 | 請勿AutoSupport 自動將此套裝組合傳送至NetApp | 錯 


| 「enableNodePrep」 | 自動管理工作節點相依性（* BETA *） | 錯 


| 「autosupportImage」 | 遙測的容器影像AutoSupport | 「NetApp/Trident自動支援：23.01」 


| 「autosupportProxy」 | 代理伺服器的位址/連接埠、用於傳送AutoSupport 「遙測」功能 | "http://proxy.example.com:8888"[] 


| 解除安裝 | 用來解除安裝Astra Trident的旗標 | 錯 


| 記錄格式 | 要使用的Astra Trident記錄格式[text、json] | "文字" 


| 「TridentImage」 | 要安裝的Astra Trident映像 | 「NetApp/Trident：21.04」 


| 「影像登錄」 | 內部登錄的路徑、格式為「<登錄FQDN >[:port]（/子路徑）」 | "k8s.gcr.io/sig-storage（k8s 1.19+）或kay.io/k8scsi" 


| 《kubeletDir | 主機上的kubelet目錄路徑 | "/var/lib/kubelet" 


| 《有線》 | 要刪除以執行完整移除Astra Trident的資源清單 |  


| 「imagePullSecrets」 | 從內部登錄擷取映像的機密 |  


| `imagePullPolicy` | 設定Trident運算子的影像提取原則。有效值包括：
`Always` 永遠拉出映像。
`IfNotPresent` 僅當節點上尚未存在映像時才提取映像。
`Never` 永遠不要拉動映像。 | `IfNotPresent` 


| 「controllerPluginNodeSelector」 | 用於 Pod 的其他節點選取器。格式與pod.spec.nodeSelector相同。 | 無預設值；選用 


| 「控制器插件」 | 覆寫 Pod 的 Kubernetes 公差。格式與po.spec.TBolerations相同。 | 無預設值；選用 


| 「nodePluginNodeSelector」 | 用於 Pod 的其他節點選取器。格式與pod.spec.nodeSelector相同。 | 無預設值；選用 


| 「nodePluginBolerations」 | 覆寫 Pod 的 Kubernetes 公差。格式與po.spec.TBolerations相同。 | 無預設值；選用 
|===

NOTE: 如需格式化Pod參數的詳細資訊、請參閱 link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["將Pod指派給節點"^]。



== 組態範例

您可以在定義時使用上述屬性 `TridentOrchestrator` 以自訂安裝。

.範例1：基本自訂組態
[%collapsible%open]
====
這是基本自訂組態的範例。

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.範例2：使用節點選取器進行部署
[%collapsible%open]
====
此範例說明如何使用節點選取器來部署Trident：

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.範例3：部署在Windows工作節點上
[%collapsible%open]
====
此範例說明如何在Windows工作節點上進行部署。

[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====