---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: 安裝 Trident 之前、您應該先檢閱這些一般系統需求。特定後端可能有其他需求。 
---
= 需求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝 Trident 之前、您應該先檢閱這些一般系統需求。特定後端可能有其他需求。



== Trident 的重要資訊

* 您必須閱讀下列有關 Trident 的重要資訊。 *

.<strong> 的 Trident </strong> 相關資訊
[%collapsible%open]
====
[]
=====
* Kubernetes 1.33 現在支援 Trident 。升級Kubernetes之前先升級Trident。
* Trident 嚴格強制在 SAN 環境中使用多重路徑組態、建議在 multipath.conf 檔案中使用值 `find_multipaths: no`。
+
使用非多重路徑組態或使用 `find_multipaths: yes` 或 `find_multipaths: smart` 多重路徑.conf檔案中的值會導致掛載失敗。Trident建議使用 `find_multipaths: no` 自21.07版本以來。



=====
====


== 支援的前端（協調器）

Trident 支援多個容器引擎和協調器、包括：

* Antos on － Prem （ VMware ）和 Antos on bare met金 片 1.16
* Kubernetes 1.27 - 1.33
* OpenShift 4.14 - 4.19（如果您打算使用 OpenShift 4.19 進行 iSCSI 節點準備，則支援的最低Trident版本為 25.06.1。）
* Rancher Kubernetes Engine 2（RKE2）v1.27.x - 1.33.x



NOTE: 雖然Trident在 Rancher Kubernetes Engine 2 (RKE2) 版本 1.27.x - 1.33.x 上受支持，但Trident目前僅在 RKE2 v1.28.5+rke2r1 上獲得認證。

Trident 也與其他完全託管且自行管理的 Kubernetes 產品合作、包括 Google Kubernetes Engine （ GKE ）、 Amazon Elastic Kubernetes Services （ EKS ）、 Azure Kubernetes Service （ aks ）、 Mirantis Kubernetes Engine （ MKE ）和 VMware Tanzu Portfolio 。

Trident 和 ONTAP 可作為的儲存供應商link:https://kubevirt.io/["KubeVirt"]。


WARNING: 在將安裝了 Trident 的 Kubernetes 叢集從 1.25 升級至 1.26 或更新版本之前link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["升級 Helm 安裝"]、請參閱。



== 支援的後端（儲存）

若要使用 Trident 、您需要下列一或多個支援的後端：

* Amazon FSX for NetApp ONTAP 產品
* Azure NetApp Files
* Cloud Volumes ONTAP
* Google Cloud NetApp Volumes
* NetApp All SAN Array ASA （ESAN）
* NetApp 有限支援下的本機 FAS、AFF 或 ASA r2（iSCSI 和 NVMe/TCP）叢集版本。請參閱。 link:https://mysupport.netapp.com/site/info/version-support["軟體版本支援"]
* NetApp HCI / Element軟體11或更新版本




== Trident 支援 KubeVirt 和 OpenShift 虛擬化

.支援的儲存驅動程式：
Trident 支援下列適用於 KubeVirt 和 OpenShift 虛擬化的 ONTAP 驅動程式：

* ONTAP-NAS
* ONTAP NAS 經濟效益
* ONTAP SAN （ iSCSI ， FCP ， NVMe over TCP ）
* ONTAP SAN 經濟型（僅限 iSCSI ）


.要考量的重點：
* 將儲存類別更新為在 OpenShift 虛擬化環境中使用 `fsType`參數（例如： `fsType: "ext4"`）。如有需要，請將 Volume 模式設定為使用中的參數 `dataVolumeTemplates`明確封鎖 `volumeMode=Block`，以通知 CDI 建立區塊資料磁碟區。
* 區塊儲存驅動程式的 _rwx 存取模式 _ ： ONTAP SAN （ iSCSI ， NVMe / TCP ， FC ）和 ONTAP SAN 經濟（ iSCSI ）驅動程式僅支援「 volumemode ：區塊」（原始裝置）。對於這些驅動程式，無法使用此參數，因為這些 `fstype`磁碟區是以原始裝置模式提供。
* 對於需要 rwx 存取模式的即時移轉工作流程，支援下列組合：
+
** NFS + `volumeMode=Filesystem`
** iSCSI + `volumeMode=Block` （原始裝置）
** NVMe / TCP + `volumeMode=Block` （原始裝置）
** FC + `volumeMode=Block` （原始裝置）






== 功能需求

下表摘要說明此 Trident 版本的可用功能、以及其支援的 Kubernetes 版本。

[cols="3"]
|===
| 功能 | Kubernetes版本 | 需要功能閘道？ 


| Trident  a| 
1.27 - 1.33
 a| 
否



| Volume Snapshot  a| 
1.27 - 1.33
 a| 
否



| 來自Volume Snapshot的PVc  a| 
1.27 - 1.33
 a| 
否



| iSCSI PV調整大小  a| 
1.27 - 1.33
 a| 
否



| 資訊雙向CHAP ONTAP  a| 
1.27 - 1.33
 a| 
否



| 動態匯出原則  a| 
1.27 - 1.33
 a| 
否



| Trident運算子  a| 
1.27 - 1.33
 a| 
否



| csi拓撲  a| 
1.27 - 1.33
 a| 
否

|===


== 已測試的主機作業系統

雖然 Trident 並未正式支援特定作業系統、但已知下列項目可以正常運作：

* OpenShift Container Platform （ AMD64 和 ARM64 ）支援的 Red Hat Enterprise Linux CoreOS （ RHCOS ）版本
* RHEL 8+ （ AMD64 和 ARM64 ）
+

NOTE: NVMe / TCP 需要 RHEL 9 或更新版本。

* Ubuntu 22.04 或更新版本（ AMD64 和 ARM64 ）
* Windows Server 2022


根據預設、 Trident 會在容器中執行、因此會在任何 Linux 工作者上執行。不過、這些工作者必須能夠使用標準的 NFS 用戶端或 iSCSI 啟動器來裝載 Trident 所提供的磁碟區、視您使用的後端而定。

「tridentctl」公用程式也可在任何這些Linux版本上執行。



== 主機組態

Kubernetes叢集中的所有工作節點都必須能夠掛載您已為Pod配置的磁碟區。若要準備工作節點、您必須根據您選擇的驅動程式來安裝 NFS 、 iSCSI 或 NVMe 工具。

link:../trident-use/worker-node-prep.html["準備工作節點"]



== 儲存系統組態

Trident 可能需要變更儲存系統、後端組態才能使用。

link:../trident-use/backends.html["設定後端"]



== Trident 連接埠

Trident 需要存取特定連接埠才能進行通訊。

link:../trident-reference/ports.html["Trident 連接埠"]



== Container映像和對應的Kubernetes版本

對於無線安裝、下列清單是安裝 Trident 所需的容器映像參考資料。使用 `tridentctl images`命令來驗證所需的容器映像清單。

[cols="2"]
|===
| Kubernetes 版本 | Container映像 


| v1.27.0 、 v1.28.0 、 v1.29.0 、 v1.30.0 、 v1.31.0 、 v1.32.0 、 v1.33.0  a| 
* Docker 。 IO/NetApp/Trident ： 25.06.0
* Docker 。 IO/NetApp/Trident 自動支援： 25.06
* registry ． k8s.io/SIG-storage / csi 置備程式： v5.2.0
* 登錄 .k8s.io/SIG-storage / csi 附加程式： v4.8.1
* 登錄 .k8s.io/SIG-storage / csi 大小調整： v1.13.2.
* 登錄 .k8s.IO/SIG-storage / csi 快照機： v8.2.1
* 登錄 .k8s.io/SIG-storage / csi 節點驅動程式登錄器： v2.13.0
* Docker 。 IO/NetApp/Trident ： 25.06.0 （選用）


|===