---
sidebar: sidebar 
permalink: trident-concepts/intro.html 
keywords: product overview, astra trident, fsx, element, astra, google cloud, cvs 
summary: Astra Trident是NetApp在Astra產品系列中所維護的完整支援開放原始碼專案。其設計旨在協助您使用業界標準介面（例如Container Storage介面（SCSI））來滿足容器化應用程式的持續需求。 
---
= 瞭解Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Astra Trident是由NetApp維護的完整支援開放原始碼專案、也是其中的一部分 link:https://docs.netapp.com/us-en/astra-family/intro-family.html["Astra產品系列"^]。其設計旨在協助您使用業界標準介面（例如Container Storage介面（SCSI））來滿足容器化應用程式的持續需求。

Astra Trident將Kubernetes叢集部署為Pod、為Kubernetes工作負載提供動態儲存協調服務。它可讓您的容器化應用程式快速輕鬆地使用NetApp廣泛產品組合中的持續儲存設備、包括ONTAP ：VMware的VMware產品組合（AFF/FAS/Select/Cloud / Amazon FSX for NetApp ONTAP ）、Element軟體（NetApp HCI / SolidFire）、Astra Data Store、Azure NetApp Files 以及VMware服務、Cloud Volumes Service 以及Google Cloud上的VMware。

Astra Trident也是NetApp Astra的一項基礎技術、運用NetApp領先業界的資料管理技術、提供快照、備份、複寫及複製等快照、備份、複寫及複製功能、為Kubernetes工作負載提供資料保護、災難恢復、可攜性及移轉使用案例。



== 支援的Kubernetes叢集架構

下列Kubernetes架構支援Astra Trident：

[cols="3*"]
|===
| Kubernetes叢集架構 | 支援 | 預設安裝 


| 單一主機、運算 | 是的  a| 
是的



| 多重主機、運算 | 是的  a| 
是的



| Master、「etcd」、運算 | 是的  a| 
是的



| 主要、基礎架構、運算 | 是的  a| 
是的

|===


== 什麼是Astra？

Astra可讓企業更輕鬆地管理、保護及搬移在公有雲內部及內部部署的Kubernetes上執行的資料豐富的容器化工作負載。Astra透過NetApp在公有雲和內部部署環境中備受肯定且廣泛的儲存產品組合、運用Astra Trident來提供持續的容器儲存設備。此外、它還提供一組豐富的進階應用程式感知資料管理功能、例如Snapshot、備份與還原、活動記錄、以及資料保護、災難/資料恢復、資料稽核、以及Kubernetes工作負載的移轉使用案例等主動複製功能。

您可以在Astra頁面註冊免費試用。



== 以取得更多資訊

* https://docs.netapp.com/us-en/astra-family/intro-family.html["NetApp Astra產品系列"]
* https://docs.netapp.com/us-en/astra/get-started/intro.html["Astra Control Service文件"^]
* https://docs.netapp.com/us-en/astra-control-center/index.html["Astra Control Center文件"^]
* https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html["Astra API文件"^]

