---
sidebar: sidebar 
permalink: trident-concepts/ontap-drivers.html 
keywords: trident backend, AFF, FAS, ONTAP Select, Cloud, Amazon FSx for NetApp ONTAP, drivers, ONTAP drivers 
summary: 瞭解如何在您的Trident安裝中建立及使用Element後端。 
---
= 驅動程式ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident提供五ONTAP 種獨特的Intel儲存驅動程式、可與ONTAP 各種叢集進行通訊。深入瞭解每個驅動程式如何處理磁碟區的建立、存取控制及其功能。



== 深入瞭ONTAP 解NetApp儲存驅動程式

[WARNING]
====
Astra Control可為使用建立的磁碟區提供無縫保護、災難恢復和移動性（在Kubernetes叢集之間移動磁碟區） `ontap-nas`、 `ontap-nas-flexgroup`和 `ontap-san` 驅動程式：請參閱 link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Astra Control複寫先決條件"^] 以取得詳細資料。

* 您必須使用 `ontap-nas` 適用於需要資料保護、災難恢復和行動力的正式作業工作負載。
* 使用 `ontap-san-economy` 當預期的Volume使用量將遠高於ONTAP 支援的容量時。
* 使用 `ontap-nas-economy` 只有在預期的Volume使用量會比ONTAP 支援的高出許多、以及 `ontap-san-economy` 無法使用驅動程式。
* 請勿使用 `ontap-nas-economy` 如果您預期需要資料保護、災難恢復或行動性、


====
[cols="5"]
|===
| 驅動程式 | 傳輸協定 | Volume模式 | 支援的存取模式 | 支援的檔案系統 


| 「ONTAP-NAS」  a| 
NFS
 a| 
檔案系統
 a| 
rwo、ROX、rwx
 a| 
」、NFS



| 《ONTAP-NANAS經濟》  a| 
NFS
 a| 
檔案系統
 a| 
rwo、ROX、rwx
 a| 
」、NFS



| 「ONTAP-NAA-flexgroup」  a| 
NFS
 a| 
檔案系統
 a| 
rwo、ROX、rwx
 a| 
」、NFS



| 「ONTAP-SAN」  a| 
iSCSI
 a| 
區塊
 a| 
rwo、ROX、rwx
 a| 
無檔案系統；原始區塊裝置



| 「ONTAP-SAN」  a| 
iSCSI
 a| 
檔案系統
 a| 
Rwo、ROX

Rwx無法在Filesystem Volume模式中使用。
 a| 
《xfs》、《ext3》、《ext4》



| 《ONTAP-san經濟》  a| 
iSCSI
 a| 
區塊
 a| 
rwo、ROX、rwx
 a| 
無檔案系統；原始區塊裝置



| 《ONTAP-san經濟》  a| 
iSCSI
 a| 
檔案系統
 a| 
Rwo、ROX

Rwx無法在Filesystem Volume模式中使用。
 a| 
《xfs》、《ext3》、《ext4》

|===

NOTE: 利用安全角色（使用者名稱/密碼）的登入認證、或是使用安裝在該叢集上的私密金鑰和憑證、來驗證後端。ONTAP ONTAP您可以使用更新現有的後端、以便從一個驗證模式移至另一個驗證模式 `tridentctl update backend`。
