---
sidebar: sidebar 
permalink: trident-concepts/provisioning.html 
keywords: provisioning, Trident 
summary: Trident 中的資源配置有兩個主要階段。第一階段會將儲存類別與一組適當的後端儲存資源池建立關聯、並在進行資源配置之前做好必要準備。第二階段包括磁碟區建立本身、需要從與擱置磁碟區的儲存類別相關的儲存池中選擇儲存池。 
---
= 資源配置
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 中的資源配置有兩個主要階段。第一階段會將儲存類別與一組適當的後端儲存資源池建立關聯、並在進行資源配置之前做好必要準備。第二階段包括磁碟區建立本身、需要從與擱置磁碟區的儲存類別相關的儲存池中選擇儲存池。



== 儲存類別關聯

將後端儲存集區與儲存類別建立關聯、需要同時仰賴儲存類別所要求的屬性及其 `storagePools`、 `additionalStoragePools`和 `excludeStoragePools`清單。當您建立儲存類別時、Trident會比較每個後端所提供的屬性和集區、以及儲存類別所要求的屬性和集區。如果儲存池的屬性和名稱符合所有要求的屬性和集區名稱、 Trident 會將該儲存集區新增至該儲存類別的適當儲存集區集。此外、 Trident 也會將清單中列出的所有儲存資源池新增至該集區 `additionalStoragePools`、即使其屬性無法滿足所有或任何儲存類別的要求屬性。您應該使用此 `excludeStoragePools`清單來覆寫及移除儲存資源池、以供儲存類別使用。每次新增後端時、 Trident 都會執行類似的程序、檢查其儲存資源池是否符合現有儲存類別的要求、並移除任何標記為排除的儲存資源池。



== Volume建立

然後， Trident 會使用儲存類別與儲存資源池之間的關聯來決定資源配置磁碟區的位置。當您建立磁碟區時、 Trident 會先取得該磁碟區儲存類別的儲存資源池集區、如果您為該磁碟區指定傳輸協定、 Trident 會移除無法提供所要求傳輸協定的儲存資源池（例如、 NetApp HCI / SolidFire 後端無法提供檔案型磁碟區、而 ONTAP NAS 後端無法提供區塊型磁碟區）。Trident 會隨機排列此結果集的順序、以利平均分配磁碟區、然後逐一重複執行、然後嘗試在每個儲存池上佈建磁碟區。如果某個項目成功、則會成功傳回、並記錄程序中發生的任何故障。Trident 只有在 * 無法在 * 所有 * 上配置可用於所要求儲存類別和傳輸協定的儲存集區時、才會傳回故障 * 。
