---
sidebar: sidebar 
permalink: trident-concepts/snapshots.html 
keywords: provisioning, astra trident 
summary: 深入瞭解Astra Trident如何為其驅動程式建立磁碟區快照。 
---
= Volume快照
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


深入瞭解Astra Trident如何為其驅動程式建立磁碟區快照。

* 對於「ONTAP-NAS」、「ONTAP-SAN」、「GCP-CVS」和「azure-NetApp-files'」等驅動程式、每個「持續Volume（PV）」都會對應FlexVol 到一個版本。因此、磁碟區快照會建立為NetApp快照。NetApp的Snapshot技術提供比競爭快照技術更高的穩定性、擴充性、可恢復性和效能。這些Snapshot複本無論在建立所需的時間、還是在儲存空間中、都能發揮極高的效率。
* 對於「ONTAP-NAS-flexgroup」驅動程式、每個「持續Volume」（PV）都會對應FlexGroup 到一個VMware。因此、磁碟區快照會建立為NetApp FlexGroup 的「資訊快照」。NetApp的Snapshot技術提供比競爭快照技術更高的穩定性、擴充性、可恢復性和效能。這些Snapshot複本無論在建立所需的時間、還是在儲存空間中、都能發揮極高的效率。
* 對於「ontap-san經濟」驅動程式、PV會對應至在共享FlexVols上建立的LUN。PV的Volume Snapshot是透過執行相關LUN的FlexClones來達成的。ONTAP的FlexClone技術幾乎可以即時建立最大資料集的複本。複本會與其父實體共用資料區塊、除了中繼資料所需的儲存空間外、不需要使用任何儲存設備。
* 對於「Poolidfire - san」驅動程式、每個PV對應至NetApp Element 在該軟體/NetApp HCI叢集上建立的LUN。Volume Snapshot以基礎LUN的元素快照來表示。這些快照是時間點複本、只佔用少量系統資源和空間。
* 使用「ONTAP-NAS」和「ONTAP-SAN」驅動程式時、ONTAP 不只是FlexVol 指時間點的複本、還會佔用FlexVol 整個過程中的空間。這可能會產生磁碟區中的可寫入空間量、以便在建立/排程快照時縮短時間。解決此問題的一種簡單方法、就是透過Kubernetes調整大小來擴充磁碟區。另一個選項是刪除不再需要的快照。當透過Kubernetes建立的Volume Snapshot被刪除時、Astra Trident會刪除相關的ONTAP 功能快照。不透過Kubernetes建立的支援快照也可以刪除。ONTAP


有了Astra Trident、您可以使用Volume Snapshot來建立新的PV。使用FlexClone技術建立這些快照的PV、以支援ONTAP 支援的支援的支援功能和CVS後端。從快照建立PV時、備份磁碟區是Snapshot父磁碟區的FlexClone。「Poolidfire - san」驅動程式使用Element軟體磁碟區複製、從快照建立PV。在此、它會從元素快照建立複本。
