---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: 如果您的環境符合需求，您可以依照下列步驟安裝 Trident Protect 。 
---
= 安裝及設定 Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果您的環境符合 Trident Protect 的要求，您可以依照下列步驟在叢集上安裝 Trident Protect 。您可以從 NetApp 取得 Trident Protect ，或從您自己的私有登錄安裝。如果您的叢集無法存取網際網路，從私有登錄安裝會很有幫助。


NOTE: 根據預設， Trident Protect 會收集支援資訊，協助處理您可能開啟的任何 NetApp 支援案例，包括叢集和託管應用程式的記錄，度量和拓撲資訊。Trident Protect 會根據每日排程將這些支援套裝組合傳送至 NetApp 。您可以選擇在安裝 Trident Protect 時停用此支援套件集合。您可以隨時手動link:trident-protect-generate-support-bundle.html["產生支援服務組合"]進行。

[role="tabbed-block"]
====
.安裝 Trident Protect from NetApp
--
.步驟
. 新增Trident Helm儲存庫：
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. 安裝 Trident Protect 客戶需求日：
+
[source, console]
----
helm install trident-protect-crds netapp-trident-protect/trident-protect-crds --version 100.2410.0 --create-namespace --namespace trident-protect
----
. 使用 Helm 以下列其中一個命令來安裝 Trident Protect 。以叢集名稱取代 `<name_of_cluster>`，該名稱將指派給叢集，用於識別叢集的備份和快照：
+
** 正常安裝 Trident Protect ：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2410.0 --create-namespace --namespace trident-protect
----
** 安裝 Trident Protect 並停用排定的每日 Trident Protect AutoSupport 支援服務套件上傳：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set autoSupport.enabled=false --set clusterName=<name_of_cluster> --version 100.2410.0 --create-namespace --namespace trident-protect
----




--
.從私有登錄安裝 Trident Protect
--
如果 Kubernetes 叢集無法存取網際網路，您可以從私有映像登錄安裝 Trident Protect 。在這些範例中，請將方括號中的值取代為環境中的資訊：

.步驟
. 將下列影像拉到您的本機電腦，更新標記，然後將它們推送到您的私人登錄：
+
[source, console]
----
netapp/controller:24.10.0
netapp/restic:24.10.0
netapp/kopia:24.10.0
netapp/trident-autosupport:24.10.0
netapp/exechook:24.10.0
netapp/resourcebackup:24.10.0
netapp/resourcerestore:24.10.0
netapp/resourcedelete:24.10.0
bitnami/kubectl:1.30.2
kubebuilder/kube-rbac-proxy:v0.16.0
----
+
例如：

+
[source, console]
----
docker pull netapp/controller:24.10.0
----
+
[source, console]
----
docker tag netapp/controller:24.10.0 <private-registry-url>/controller:24.10.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:24.10.0
----
. 建立 Trident Protect 系統命名空間：
+
[source, console]
----
kubectl create ns trident-protect
----
. 登入登錄：
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. 建立用於私人登錄驗證的拉出密碼：
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. 新增Trident Helm儲存庫：
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. 建立名稱包含下列 Trident Protect 設定的檔案 `protectValues.yaml`：
+
[source, yaml]
----
image:
  registry: <private-registry-url>
imagePullSecrets:
- name: regcred
controller:
  image:
    registry: <private-registry-url>
rbacProxy:
  image:
    registry: <private-registry-url>
crCleanup:
  imagePullSecrets:
  - name: regcred
webhooksCleanup:
  imagePullSecrets:
  - name: regcred
----
. 安裝 Trident Protect 客戶需求日：
+
[source, console]
----
helm install trident-protect-crds netapp-trident-protect/trident-protect-crds --version 100.2410.0 --create-namespace --namespace trident-protect
----
. 使用 Helm 以下列其中一個命令來安裝 Trident Protect 。以叢集名稱取代 `<name_of_cluster>`，該名稱將指派給叢集，用於識別叢集的備份和快照：
+
** 正常安裝 Trident Protect ：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2410.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
** 安裝 Trident Protect 並停用排定的每日 Trident Protect AutoSupport 支援服務套件上傳：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set autoSupport.enabled=false --set clusterName=<name_of_cluster> --version 100.2410.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----




--
====