---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: 首先，請確認您的營運環境，應用程式叢集，應用程式和授權是否準備就緒。確保您的環境符合這些需求，以部署及操作 Trident Protect 。 
---
= Trident 保護需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
首先，請確認您的營運環境，應用程式叢集，應用程式和授權是否準備就緒。確保您的環境符合這些需求，以部署及操作 Trident Protect 。



== Trident 保護 Kubernetes 相容性

Trident Protect 可與多種完全託管且自我管理的 Kubernetes 產品相容，包括：

* Amazon Elastic Kubernetes Service （ EKS ）
* Google Kubernetes Engine（GKE）
* Microsoft Azure Kubernetes服務（英文）
* Red Hat OpenShift
* SUSE Rancher
* VMware Tanzu產品組合
* 上游Kubernetes




== Trident 保護儲存後端相容性

Trident Protect 支援下列儲存設備後端：

* Amazon FSX for NetApp ONTAP 產品
* Cloud Volumes ONTAP
* ONTAP 儲存陣列
* Google Cloud NetApp Volumes
* Azure NetApp Files


確保您的儲存後端符合下列需求：

* 確保連接至叢集的 NetApp 儲存設備使用 Astra Trident 24.02 或更新版本（建議使用 Trident 24.10 ）。
+
** 如果 Astra Trident 早於 24.06.1 版，且您計畫使用 NetApp SnapMirror 災難恢復功能，則需要手動啟用 Astra 控制項資源配置程式。


* 確保您擁有最新的 Astra 控制備份程式（預設為 Astra Trident 24.06.1 ）。
* 確保您擁有 NetApp ONTAP 儲存後端。
* 請確定您已設定物件儲存貯體以儲存備份。
* 建立您計畫用於應用程式或應用程式資料管理作業的任何應用程式命名空間。Trident Protect 不會為您建立這些命名空間；如果您在自訂資源中指定不存在的命名空間，則作業將會失敗。




== NAS 經濟容量需求

Trident Protect 支援 NAS 經濟型磁碟區的備份與還原作業。目前不支援快照，複製和 SnapMirror 複寫至 NAS 經濟型磁碟區。您需要為打算搭配 Trident Protect 使用的每個 NAS 經濟型磁碟區啟用快照目錄。

[NOTE]
====
某些應用程式與使用 Snapshot 目錄的磁碟區不相容。對於這些應用程式，您需要在 ONTAP 儲存系統上執行下列命令，以隱藏快照目錄：

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
您可以針對每個 NAS 經濟型磁碟區執行下列命令，以您要變更的磁碟區 UUID 取代，來啟用 Snapshot 目錄 `<volume-UUID>`：

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: 您可以將 Trident 後端組態選項設定為，為 `true`新的磁碟區預設啟用快照目錄 `snapshotDir`。現有的磁碟區不受影響。



== 使用 KubeVirt VM 保護資料

當您保護在 KubeVirt VM 上執行的應用程式時， Trident Protect 24.10 和 24.10.1 及更新版本的行為會有所不同。對於這兩個版本，您可以在資料保護作業期間啟用或停用檔案系統凍結和解除凍結。

[NOTE]
====
對於所有 Trident Protect 版本，若要在 OpenShift 環境中啟用或停用自動凍結功能，您可能需要授予應用程式命名空間的權限。例如：

[source, console]
----
oc adm policy add-scc-to-user privileged -z default -n <application-namespace>
----
====
.Trident Protect 24.10
Trident Protect 24.10 無法在資料保護作業期間，自動確保 KubeVirt VM 檔案系統的狀態一致。如果您想要使用 Trident Protect 24.10 來保護 KubeVirt VM 資料，則必須在資料保護作業之前，手動啟用檔案系統的凍結 / 取消凍結功能。如此可確保檔案系統處於一致的狀態。

您可以將 Trident Protect 24.10 設定為在資料保護作業期間管理 VM 檔案系統的凍結和取消凍結link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["設定虛擬化"^]，然後使用下列命令：

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
.Trident Protect 24.10.1 及更新版本
從 Trident Protect 24.10.1 開始， Trident Protect 會在資料保護作業期間，自動凍結和取消凍結 KubeVirt 檔案系統。您也可以使用下列命令停用此自動行為：

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----


== SnapMirror 複寫需求

NetApp SnapMirror 可與 Trident Protect 搭配使用，適用於下列 ONTAP 解決方案：

* NetApp ASA
* NetApp AFF
* NetApp FAS
* NetApp ONTAP Select
* NetApp Cloud Volumes ONTAP
* Amazon FSX for NetApp ONTAP 產品




=== SnapMirror 複寫的 ONTAP 叢集需求

如果您打算使用 SnapMirror 複寫，請確保 ONTAP 叢集符合下列需求：

* * Astra 控制備份程式或 Trident * ： Astra 控制備份程式或 Trident 必須同時存在於使用 ONTAP 作為後端的來源叢集和目的地 Kubernetes 叢集上。Trident Protect 使用下列驅動程式所支援的儲存類別，以 NetApp SnapMirror 技術支援複寫：
+
** 「ONTAP-NAS」
** 「ONTAP-SAN」


* * 授權 * ：使用資料保護套件的 ONTAP SnapMirror 非同步授權必須同時在來源和目的地 ONTAP 叢集上啟用。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["SnapMirror授權概述ONTAP"^] 。




=== SnapMirror 複寫的對等考量

如果您計畫使用儲存後端對等，請確保您的環境符合下列需求：

* * 叢集與 SVM* ：必須對 ONTAP 儲存設備的後端進行對等處理。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap/peering/index.html["叢集與SVM對等概觀"^] 。
+

NOTE: 確保兩個 ONTAP 叢集之間複寫關係中使用的 SVM 名稱是唯一的。

* *Astra 控制資源配置程式或 Trident 和 SVM* ：對等的遠端 SVM 必須可用於目的地叢集上的 Astra 控制資源配置程式或 Trident 。
* * 託管後端 * ：您需要在 Trident Protect 中新增及管理 ONTAP 儲存後端，才能建立複寫關係。
* *NVMe over TCP* ： Trident Protect 不支援 NetApp SnapMirror 複寫，用於使用 NVMe over TCP 傳輸協定的儲存後端。




=== 用於 SnapMirror 複寫的 Trident / ONTAP 組態

Trident Protect 要求您至少設定一個儲存後端，以支援來源叢集和目的地叢集的複寫。如果來源叢集和目的地叢集相同、則目的地應用程式應使用不同於來源應用程式的儲存後端、以獲得最佳恢復能力。
