---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: 首先，請驗證您的運行環境、應用程式叢集、應用程式和授權是否已準備就緒。確保您的環境符合部署和執行Trident Protect 的這些要求。 
---
= Trident保護要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
首先，請驗證您的運行環境、應用程式叢集、應用程式和授權是否已準備就緒。確保您的環境符合部署和執行Trident Protect 的這些要求。



== Trident Protect Kubernetes 叢集相容性

Trident Protect 與各種完全託管和自架的 Kubernetes 產品相容，包括：

* Amazon Elastic Kubernetes Service （ EKS ）
* Google Kubernetes Engine（GKE）
* Microsoft Azure Kubernetes服務（英文）
* Red Hat OpenShift
* SUSE Rancher
* VMware Tanzu產品組合
* 上游Kubernetes


[NOTE]
====
* Trident Protect備份僅支援Linux運算節點。Windows 運算節點不支援備份作業。
* 確保安裝Trident Protect 的叢集已配置正在執行中的快照控制器和相關的 CRD。若要安裝快照控制器，請參閱 https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["這些指示"]。
* 確保至少存在一個 VolumeSnapshotClass。更多信息，請參閱link:https://docs.netapp.com/us-en/trident_main/trident-reference/objects.html#kubernetes-volumesnapshotclass-objects["Volume SnapshotClass"]。


====


== Trident Protect 儲存後端相容性

Trident Protect 支援以下儲存後端：

* Amazon FSX for NetApp ONTAP 產品
* Cloud Volumes ONTAP
* ONTAP 儲存陣列
* Google Cloud NetApp Volumes
* Azure NetApp Files


確保您的儲存後端符合下列需求：

* 確保連接到叢集的 NetApp 儲存裝置使用 Trident 24.02 或更新版本（建議使用 Trident 24.10）。


* 確保您擁有 NetApp ONTAP 儲存後端。
* 請確定您已設定物件儲存貯體以儲存備份。
* 建立您計劃用於應用程式或應用程式資料管理作業的任何應用程式命名空間。Trident Protect 不會為您建立這些命名空間；如果您在自訂資源中指定了不存在的命名空間，則操作將會失敗。




== NAS 經濟容量需求

Trident Protect 支援對 nas-economy 磁碟區進行備份和復原作業。目前不支援將快照、克隆和SnapMirror複製到 nas-economy 磁碟區。您需要為計劃與Trident Protect 一起使用的每個 nas-economy 磁碟區啟用快照目錄。

[NOTE]
====
某些應用程式與使用 Snapshot 目錄的磁碟區不相容。對於這些應用程式，您需要在 ONTAP 儲存系統上執行下列命令，以隱藏快照目錄：

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
您可以針對每個 NAS 經濟型磁碟區執行下列命令，以您要變更的磁碟區 UUID 取代，來啟用 Snapshot 目錄 `<volume-UUID>`：

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: 您可以將 Trident 後端組態選項設定為，為 `true`新的磁碟區預設啟用快照目錄 `snapshotDir`。現有的磁碟區不受影響。



== 使用 KubeVirt VM 保護資料

Trident Protect 在資料保護作業期間為 KubeVirt 虛擬機器提供檔案系統凍結和解凍功能，以確保資料一致性。虛擬機器凍結操作的配置方法和預設行為在Trident Protect 的不同版本中有所不同，較新的版本透過 Helm chart 參數提供了簡化的配置。


NOTE: 在恢復操作期間，任何 `VirtualMachineSnapshots`為虛擬機器 (VM) 所建立的資料不會被復原。

.Trident Protect 25.10 及更新版本
[%collapsible%open]
====
Trident Protect 在資料保護作業期間自動凍結和解凍 KubeVirt 檔案系統，以確保一致性。從Trident Protect 25.10 開始，您可以使用以下方法停用此行為： `vm.freeze` Helm Chart 安裝過程中的參數。此參數預設啟用。

[source, console]
----
helm install ... --set vm.freeze=false ...
----
====
.Trident Protect 24.10.1 至 25.06
[%collapsible]
====
從Trident Protect 24.10.1 開始， Trident Protect 會在資料保護作業期間自動凍結和解凍 KubeVirt 檔案系統。您也可以使用以下命令停用此自動行為：

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----
====
.Trident Protect 24.10
[%collapsible]
====
Trident Protect 24.10 在資料保護作業期間不會自動確保 KubeVirt VM 檔案系統的一致性狀態。如果您想使用Trident Protect 24.10 保護您的 KubeVirt VM 數據，則需要在執行資料保護作業之前手動啟用檔案系統的凍結/解凍功能。這樣可以確保檔案系統處於一致狀態。

您可以設定Trident Protect 24.10 來管理資料保護作業期間 VM 檔案系統的凍結與解凍。link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["設定虛擬化"^]然後使用以下命令：

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
====


== SnapMirror 複寫需求

NetApp SnapMirror複製功能可與Trident Protect 搭配使用，適用於下列ONTAP解決方案：

* 內部部署 NetApp FAS ， AFF 和 ASA 叢集
* NetApp ONTAP Select
* NetApp Cloud Volumes ONTAP
* Amazon FSX for NetApp ONTAP 產品




=== SnapMirror 複寫的 ONTAP 叢集需求

如果您打算使用 SnapMirror 複寫，請確保 ONTAP 叢集符合下列需求：

* * NetApp Trident *：使用ONTAP作為後端服務的來源 Kubernetes 叢集和目標 Kubernetes 叢集上都必須存在NetApp Trident 。Trident Protect 支援使用NetApp SnapMirror技術進行複製，該技術使用以下驅動程式支援的儲存類別：
+
** `ontap-nas` ：NFS
** `ontap-san` ：iSCSI
** `ontap-san` ：足球俱樂部
** `ontap-san` ：NVMe/TCP（要求最低 ONTAP 版本 9.15.1）


* * 授權 * ：使用資料保護套件的 ONTAP SnapMirror 非同步授權必須同時在來源和目的地 ONTAP 叢集上啟用。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["SnapMirror授權概述ONTAP"^] 。
+
從 ONTAP 9.10.1 開始、所有授權都會以 NetApp 授權檔案（ NLF ）的形式交付、這是一個可啟用多項功能的單一檔案。如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One 隨附授權"^] 。

+

NOTE: 僅支援 SnapMirror 非同步保護。





=== SnapMirror 複寫的對等考量

如果您計畫使用儲存後端對等，請確保您的環境符合下列需求：

* * 叢集與 SVM* ：必須對 ONTAP 儲存設備的後端進行對等處理。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap/peering/index.html["叢集與SVM對等概觀"^] 。
+

NOTE: 確保兩個 ONTAP 叢集之間複寫關係中使用的 SVM 名稱是唯一的。

* *NetApp Trident 與 SVM*：對等遠端 SVM 必須可供目標叢集上的 NetApp Trident 使用。
* *託管後端*：您需要在Trident Protect 中新增和管理ONTAP儲存後端，以建立複製關係。




=== 用於 SnapMirror 複寫的 Trident / ONTAP 組態

Trident Protect 要求您至少設定一個支援來源叢集和目標叢集複製的儲存後​​端。如果來源叢集和目標叢集相同，為了獲得最佳彈性，目標應用程式應該使用與來源應用程式不同的儲存後端。



=== SnapMirror複製的 Kubernetes 叢集要求

確保您的 Kubernetes 叢集符合以下要求：

* *AppVault 可存取性*：來源叢集和目標叢集都必須具有網路存取權限，才能從 AppVault 讀取和寫入應用程式物件複製。
* *網路連線*：設定防火牆規則、儲存桶權限和 IP 允許列表，以實現跨 WAN 的叢集和 AppVault 之間的通訊。



NOTE: 許多企業環境在 WAN 連線中實施嚴格的防火牆策略。在配置複製之前，請與您的基礎設施團隊驗證這些網路需求。
