---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: 如果您的環境符合要求，您可以依照下列步驟安裝Trident Protect。 
---
= 安裝並設定Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果您的環境符合Trident Protect 的要求，您可以依照下列步驟在叢集上安裝Trident Protect。您可以從NetApp取得Trident Protect，或從您自己的私人註冊表中安裝它。如果您的叢集無法存取互聯網，從私有註冊表安裝會很有幫助。



== 安裝Trident Protect

[role="tabbed-block"]
====
.從NetApp安裝Trident Protect
--
.步驟
. 新增Trident Helm儲存庫：
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. 使用 Helm 安裝Trident Protect。代替 `<name-of-cluster>`集群名稱將分配給集群，並用於標識集群的備份和快照：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2510.0 --create-namespace --namespace trident-protect
----
. （選用）若要啟用偵錯日誌記錄（建議用於故障排除），請使用：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect
----
+
偵錯日誌記錄有助於NetApp支援人員排除故障，而無需變更日誌等級或重現問題。



--
.從私人註冊表安裝Trident Protect
--
如果您的 Kubernetes 叢集無法存取互聯網，您可以從私人鏡像倉庫安裝Trident Protect。在這些範例中，請將括號中的值替換為您環境中的資訊：

.步驟
. 將下列影像拉到您的本機電腦，更新標記，然後將它們推送到您的私人登錄：
+
[source, console]
----
docker.io/netapp/controller:25.10.0
docker.io/netapp/restic:25.10.0
docker.io/netapp/kopia:25.10.0
docker.io/netapp/kopiablockrestore:25.10.0
docker.io/netapp/trident-autosupport:25.10.0
docker.io/netapp/exechook:25.10.0
docker.io/netapp/resourcebackup:25.10.0
docker.io/netapp/resourcerestore:25.10.0
docker.io/netapp/resourcedelete:25.10.0
docker.io/netapp/trident-protect-utils:v1.0.0
----
+
例如：

+
[source, console]
----
docker pull docker.io/netapp/controller:25.10.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.10.0 <private-registry-url>/controller:25.10.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.10.0
----
+

NOTE: 要取得 Helm Chart，首先需要在可以存取網路的電腦上下載 Helm Chart。 `helm pull trident-protect --version 100.2510.0 --repo https://netapp.github.io/trident-protect-helm-chart`然後複製結果 `trident-protect-100.2510.0.tgz` 將檔案複製到您的離線環境並進行安裝 `helm install trident-protect ./trident-protect-100.2510.0.tgz` 而不是在最後一步使用存儲庫引用。

. 建立Trident Protect 系統命名空間：
+
[source, console]
----
kubectl create ns trident-protect
----
. 登入登錄：
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. 建立用於私人登錄驗證的拉出密碼：
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. 新增Trident Helm儲存庫：
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. 建立一個名為的文件 `protectValues.yaml`。請確保其中包含以下Trident Protect 設定：
+
[source, yaml]
----
---
imageRegistry: <private-registry-url>
imagePullSecrets:
  - name: regcred
----
+

NOTE: 這 `imageRegistry`和 `imagePullSecrets`這些值適用於所有組件影像，包括 `resourcebackup`和 `resourcerestore`。如果您將鏡像推送到註冊表中的特定儲存庫路徑（例如， `example.com:443/my-repo`），請在登錄欄位中包含完整路徑。這將確保所有圖像都從此處提取。 `<private-registry-url>/<image-name>:<tag>`。

. 使用 Helm 安裝Trident Protect。代替 `<name_of_cluster>`集群名稱將分配給集群，並用於標識集群的備份和快照：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
. （選用）若要啟用偵錯日誌記錄（建議用於故障排除），請使用：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
+
偵錯日誌記錄有助於NetApp支援人員排除故障，而無需變更日誌等級或重現問題。



--
====

NOTE: 有關其他 Helm Chart 設定選項，包括AutoSupport設定和命名空間過濾，請參閱 link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["自訂Trident Protect 安裝"]。
