---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: 深入瞭解tridentctl、這是一個命令列公用程式、可讓您輕鬆存取Trident。 
---
= 使用 Tridentctl 管理 Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 https://github.com/NetApp/trident/releases["Trident安裝程式套裝組合"^] 包括 `tridentctl` 命令列公用程式、提供 Astra Trident 的簡單存取。擁有足夠權限的 Kubernetes 使用者可以使用它來安裝 Astra Trident 或管理內含 Astra Trident Pod 的命名空間。



== 命令和全域旗標

您可以執行 `tridentctl help` 取得的可用命令清單 `tridentctl` 或附加 `--help` 標記至任何命令、以取得該特定命令的選項和旗標清單。

使用量::


[listing]
----
tridentctl [command] [--optional-flag]
----
Astra Trident `tridentctl` 公用程式支援下列命令和全域旗標。

.命令
[%collapsible]
====
`create`:: 新增資源至 Astra Trident 。
`delete`:: 從 Astra Trident 移除一或多個資源。
`get`:: 從 Astra Trident 取得一或多個資源。
`help`:: 任何命令的相關說明。
`images`:: 列印 Astra Trident 所需的容器影像表格。
`import`:: 將現有資源匯入 Astra Trident 。
`install`:: 安裝Astra Trident。
`logs`:: 列印 Astra Trident 的記錄。
`send`:: 從 Astra Trident 傳送資源。
解除安裝:: 解除安裝 Astra Trident 。
`update`:: 修改 Astra Trident 中的資源。
`update backend state`:: 暫時暫停後端作業。
`upgrade`:: 升級 Astra Trident 中的資源。
「分度」:: 列印 Astra Trident 的版本。


====
.全域旗標
[%collapsible]
====
`-d`、 `--debug`:: 除錯輸出。
`-h`、 `--help`:: 的說明 `tridentctl`。
`-n`、 `--namespace string`:: Astra Trident 部署的命名空間。
`-o`、 `--output string`:: 輸出格式。json之一| yaml| name| wl| ps（預設）。
`-s`、 `--server string`:: Astra Trident REST 介面的位址 / 連接埠。
+
--

WARNING: Trident REST介面可設定為偵聽、僅適用於127.0.0.1（適用於IPV4）或[:1]（適用於IPv6）。

--


====


== 命令選項和旗標



=== `create`

使用 `create` 命令以新增資源至Astra Trident。

使用量::


[listing]
----
tridentctl create [option]
----
選項:: 新增後端至 Astra Trident 。




=== `delete`

使用 `delete` 從Astra Trident移除一或多個資源的命令。

使用量::


[listing]
----
tridentctl delete [option]
----
選項:: 從 Astra Trident 刪除一或多個儲存後端。
`snapshot`:: 從 Astra Trident 刪除一或多個 Volume 快照。
`storageclass`:: 從 Astra Trident 刪除一或多個儲存類別。
`volume`:: 從 Astra Trident 刪除一或多個儲存磁碟區。




=== `get`

使用 `get` 從Astra Trident取得一或多個資源的命令。

使用量::


[listing]
----
tridentctl get [option]
----
選項:: 從 Astra Trident 取得一或多個儲存設備後端。
`snapshot`:: 從 Astra Trident 取得一或多個快照。
`storageclass`:: 從 Astra Trident 取得一或多個儲存類別。
`volume`:: 從 Astra Trident 取得一或多個 Volume 。
旗標:: Volume 說明。
`--parentOfSubordinate string`:: 將查詢限制在從屬來源 Volume 。
`--subordinateOf string`:: 將查詢限制在 Volume 的從屬。




=== `images`

使用 `images` 用於列印 Astra Trident 所需容器影像表格的旗標。

使用量::


[listing]
----
tridentctl images [flags]
----
旗標:: 影像說明。
`-v`、 `--k8s-version string`:: Kubernetes 叢集的語義版本。




=== `import volume`

使用 `import volume` 將現有磁碟區匯入Astra Trident的命令。

使用量::


[listing]
----
tridentctl import volume <backendName> <volumeName> [flags]
----
別名:: `volume, v`
旗標:: YAML 或 JSON PVC 檔案路徑。
`-h`、 `--help`:: Volume 說明。
`--no-manage`:: 僅建立 PV/PVC 。不要假設磁碟區生命週期管理。




=== `install`

使用 `install` 安裝Astra Trident的旗標。

使用量::


[listing]
----
tridentctl install [flags]
----
旗標:: AutoSupport 遙測的容器映像（預設為「 NetApp/trident autosupport ： <current-version> 」）。
`--autosupport-proxy string`:: 用於傳送 AutoSupport 遙測的 Proxy 位址 / 連接埠。
`--enable-node-prep`:: 嘗試在節點上安裝必要的套件。
`--generate-custom-yaml`:: 產生 YAML 檔案、無需安裝任何項目。
`-h`、 `--help`:: 安裝說明。
`--http-request-timeout`:: 覆寫 Trident 控制器 REST API 的 HTTP 要求逾時（預設為 1m30s ）。
`--image-registry string`:: 內部映像登錄的位址 / 連接埠。
`--k8s-timeout duration`:: 所有 Kubernetes 作業的逾時時間（預設為 30 個月）。
`--kubelet-dir string`:: kubelet 內部狀態的主機位置（預設為「 /var/lib/kubelet 」）。
`--log-format string`:: Astra Trident 記錄格式（文字、 json ）（預設「文字」）。
`--pv string`:: Astra Trident 使用的舊版 PV 名稱、可確保不存在（預設為「 trident 」）。
`--pvc string`:: Astra Trident 使用的舊版 PVC 名稱、可確保不存在（預設為「 trident 」）。
`--silence-autosupport`:: 請勿將 AutoSupport 套裝組合自動傳送至 NetApp （預設為 true ）。
`--silent`:: 在安裝期間停用大部分輸出。
`--trident-image string`:: 要安裝的 Astra Trident 映像。
`--use-custom-yaml`:: 使用安裝目錄中現有的任何 YAML 檔案。
`--use-ipv6`:: 使用 IPv6 進行 Astra Trident 的通訊。




=== `logs`

使用 `logs` 用於列印Astra Trident記錄的旗標。

使用量::


[listing]
----
tridentctl logs [flags]
----
旗標:: 除非另有指定、否則請使用所有記錄建立支援歸檔。
`-h`、 `--help`:: 記錄說明。
`-l`、 `--log string`:: 要顯示的 Astra Trident 記錄。其中一個trident | auto| trident運算子| all（預設為「自動」）。
`--node string`:: 用來收集節點 Pod 記錄的 Kubernetes 節點名稱。
`-p`、 `--previous`:: 取得先前容器執行個體的記錄（如果存在）。
`--sidecars`:: 取得 sidecar 容器的記錄。




=== `send`

使用 `send` 從Astra Trident傳送資源的命令。

使用量::


[listing]
----
tridentctl send [option]
----
選項:: 將 AutoSupport 歸檔傳送至 NetApp 。




=== 解除安裝

使用 `uninstall` 解除安裝Astra Trident的旗標。

使用量::


[listing]
----
tridentctl uninstall [flags]
----
旗標:: 解除安裝說明。
`--silent`:: 在解除安裝期間停用大部分的輸出。




=== `update`

使用 `update` 命令以修改 Astra Trident 中的資源。

使用量::


[listing]
----
tridentctl update [option]
----
選項:: 更新 Astra Trident 中的後端。




=== `update backend state`

使用 `update backend state` 暫停或恢復後端作業的命令。

使用量::


[listing]
----
tridentctl update backend state <backend-name> [flag]
----
旗標:: 設定為 `suspended` 暫停後端作業。設定為 `normal` 以恢復後端作業。設定為時 `suspended`：
+
--
* `AddVolume`、 `CloneVolume`、 `Import Volume`、 `ResizeVolume` 已暫停。
* `PublishVolume`、 `UnPublishVolume`、 `CreateSnapshot`、 `GetSnapshot`、 `RestoreSnapshot`、 `DeleteSnapshot`、 `RemoveVolume`、 `GetVolumeExternal`、 `ReconcileNodeAccess` 保持可用狀態。


--
`-h`、 `--help`:: 後端狀態說明。




=== 「分度」

使用 `version` 用於列印版本的旗標 `tridentctl` 以及執行中的Trident服務。

使用量::


[listing]
----
tridentctl version [flags]
----
旗標:: 僅限用戶端版本（不需要伺服器）。
`-h, --help`:: 版本說明。

